
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "org_slicer_libs_qMRMLWidgets.h"

void PythonQt_init_org_slicer_libs_qMRMLWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qMRMLCaptureToolBar::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLCaptureToolBar>);
  

  PythonQt::self()->registerClass(
  &qMRMLCheckableNodeComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLCheckableNodeComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLClipNodeWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLClipNodeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLCollapsibleButton::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLCollapsibleButton>);
  

  PythonQt::self()->registerClass(
  &qMRMLColorListView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLColorListView>);
  

  PythonQt::self()->registerClass(
  &qMRMLColorModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLColorModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLColorPickerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLColorPickerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLColorTableComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLColorTableComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLColorTableView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLColorTableView>);
  

  PythonQt::self()->registerClass(
  &qMRMLCoordinatesWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLCoordinatesWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLDisplayNodeWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLDisplayNodeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLDisplayNodeViewComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLDisplayNodeViewComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLLabelComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLLabelComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLEventBrokerConnection::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLEventBrokerConnection>);
  

  PythonQt::self()->registerClass(
  &qMRMLEventBrokerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLEventBrokerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLEventLogger::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLEventLogger>);
  

  PythonQt::self()->registerClass(
  &qMRMLEventLoggerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLEventLoggerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLItemDelegate::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLItemDelegate>);
  

  PythonQt::self()->registerClass(
  &qMRMLLayoutManager::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLLayoutManager>);
  

  PythonQt::self()->registerClass(
  &qMRMLLayoutViewFactory::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLLayoutViewFactory>);
  

  PythonQt::self()->registerClass(
  &qMRMLLayoutWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLLayoutWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLLinearTransformSlider::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLLinearTransformSlider>);
  

  PythonQt::self()->registerClass(
  &qMRMLListWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLListWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMatrixWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMatrixWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLModelInfoWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLModelInfoWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLNavigationView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLNavigationView>);
  

  PythonQt::self()->registerClass(
  &qMRMLNodeAttributeTableView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLNodeAttributeTableView>);
  

  PythonQt::self()->registerClass(
  &qMRMLNodeAttributeTableWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLNodeAttributeTableWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLNodeComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLNodeComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLNodeFactory::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLNodeFactory>);
  

  PythonQt::self()->registerClass(
  &qMRMLPlotWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLPlotWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLPlotView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLPlotView>);
  

  PythonQt::self()->registerClass(
  &qMRMLPlotViewControllerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLPlotViewControllerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLRangeWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLRangeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLROIWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLROIWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLScalarInvariantComboBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLScalarInvariantComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLScalarsDisplayWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLScalarsDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneCategoryModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneCategoryModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneColorTableModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneColorTableModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneFactoryWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneFactoryWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneViewMenu::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneViewMenu>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneTransformModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneTransformModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneHierarchyModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneHierarchyModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSceneDisplayableModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSceneDisplayableModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLScreenShotDialog::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLScreenShotDialog>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentSelectorWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentSelectorWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliceControllerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliceControllerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliceInformationWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliceInformationWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliceVerticalControllerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliceVerticalControllerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliceView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliceView>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliceWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliceWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSliderWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSliderWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSortFilterHierarchyProxyModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSortFilterHierarchyProxyModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSortFilterProxyModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSortFilterProxyModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSpinBox::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSpinBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLTableModel::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTableModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLTableView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTableView>);
  

  PythonQt::self()->registerClass(
  &qMRMLTableViewControllerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTableViewControllerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLTableWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTableWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLThreeDView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLThreeDView>);
  

  PythonQt::self()->registerClass(
  &qMRMLThreeDViewControllerWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLThreeDViewControllerWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLThreeDViewInformationWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLThreeDViewInformationWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLThreeDWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLThreeDWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLTransformSliders::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTransformSliders>);
  

  PythonQt::self()->registerClass(
  &qMRMLTreeView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLTreeView>);
  

  PythonQt::self()->registerClass(
  &qMRMLUtils::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLUtils>);
  

  PythonQt::self()->registerClass(
  &qMRMLViewControllerBar::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLViewControllerBar>);
  

  PythonQt::self()->registerClass(
  &qMRMLVolumeInfoWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLVolumeInfoWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLVolumeThresholdWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLVolumeThresholdWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLVolumeWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLVolumeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLWindowLevelWidget::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLWindowLevelWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLExpandingWebView::staticMetaObject, "qMRMLWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLExpandingWebView>);
  
}
