
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __org_slicer_libs_qMRMLWidgets_h
#define __org_slicer_libs_qMRMLWidgets_h

#include <QObject>
#include "qMRMLCaptureToolBar.h"
#include "qMRMLCheckableNodeComboBox.h"
#include "qMRMLClipNodeWidget.h"
#include "qMRMLCollapsibleButton.h"
#include "qMRMLColorListView.h"
#include "qMRMLColorModel.h"
#include "qMRMLColorPickerWidget.h"
#include "qMRMLColorTableComboBox.h"
#include "qMRMLColorTableView.h"
#include "qMRMLCoordinatesWidget.h"
#include "qMRMLDisplayNodeWidget.h"
#include "qMRMLDisplayNodeViewComboBox.h"
#include "qMRMLLabelComboBox.h"
#include "qMRMLEventBrokerConnection.h"
#include "qMRMLEventBrokerWidget.h"
#include "qMRMLEventLogger.h"
#include "qMRMLEventLoggerWidget.h"
#include "qMRMLItemDelegate.h"
#include "qMRMLLayoutManager.h"
#include "qMRMLLayoutViewFactory.h"
#include "qMRMLLayoutWidget.h"
#include "qMRMLLinearTransformSlider.h"
#include "qMRMLListWidget.h"
#include "qMRMLMatrixWidget.h"
#include "qMRMLModelInfoWidget.h"
#include "qMRMLNavigationView.h"
#include "qMRMLNodeAttributeTableView.h"
#include "qMRMLNodeAttributeTableWidget.h"
#include "qMRMLNodeComboBox.h"
#include "qMRMLNodeFactory.h"
#include "qMRMLPlotWidget.h"
#include "qMRMLPlotView.h"
#include "qMRMLPlotViewControllerWidget.h"
#include "qMRMLRangeWidget.h"
#include "qMRMLROIWidget.h"
#include "qMRMLScalarInvariantComboBox.h"
#include "qMRMLScalarsDisplayWidget.h"
#include "qMRMLSceneCategoryModel.h"
#include "qMRMLSceneColorTableModel.h"
#include "qMRMLSceneFactoryWidget.h"
#include "qMRMLSceneModel.h"
#include "qMRMLSceneViewMenu.h"
#include "qMRMLSceneTransformModel.h"
#include "qMRMLSceneHierarchyModel.h"
#include "qMRMLSceneDisplayableModel.h"
#include "qMRMLScreenShotDialog.h"
#include "qMRMLSegmentSelectorWidget.h"
#include "qMRMLSliceControllerWidget.h"
#include "qMRMLSliceInformationWidget.h"
#include "qMRMLSliceVerticalControllerWidget.h"
#include "qMRMLSliceView.h"
#include "qMRMLSliceWidget.h"
#include "qMRMLSliderWidget.h"
#include "qMRMLSortFilterHierarchyProxyModel.h"
#include "qMRMLSortFilterProxyModel.h"
#include "qMRMLSpinBox.h"
#include "qMRMLTableModel.h"
#include "qMRMLTableView.h"
#include "qMRMLTableViewControllerWidget.h"
#include "qMRMLTableWidget.h"
#include "qMRMLThreeDView.h"
#include "qMRMLThreeDViewControllerWidget.h"
#include "qMRMLThreeDViewInformationWidget.h"
#include "qMRMLThreeDWidget.h"
#include "qMRMLTransformSliders.h"
#include "qMRMLTreeView.h"
#include "qMRMLUtils.h"
#include "qMRMLViewControllerBar.h"
#include "qMRMLVolumeInfoWidget.h"
#include "qMRMLVolumeThresholdWidget.h"
#include "qMRMLVolumeWidget.h"
#include "qMRMLWidget.h"
#include "qMRMLWindowLevelWidget.h"
#include "qMRMLExpandingWebView.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLCaptureToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLCaptureToolBar* new_qMRMLCaptureToolBar(QWidget*  parent = 0)
    {
    return new qMRMLCaptureToolBar(parent);
    }
  void delete_qMRMLCaptureToolBar(qMRMLCaptureToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLCheckableNodeComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLCheckableNodeComboBox* new_qMRMLCheckableNodeComboBox(QWidget*  parent = 0)
    {
    return new qMRMLCheckableNodeComboBox(parent);
    }
  void delete_qMRMLCheckableNodeComboBox(qMRMLCheckableNodeComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLClipNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLClipNodeWidget* new_qMRMLClipNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLClipNodeWidget(parent);
    }
  void delete_qMRMLClipNodeWidget(qMRMLClipNodeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLCollapsibleButton : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLCollapsibleButton* new_qMRMLCollapsibleButton(QWidget*  parent = 0)
    {
    return new qMRMLCollapsibleButton(parent);
    }
  void delete_qMRMLCollapsibleButton(qMRMLCollapsibleButton* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorListView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorListView* new_qMRMLColorListView(QWidget*  parent = 0)
    {
    return new qMRMLColorListView(parent);
    }
  void delete_qMRMLColorListView(qMRMLColorListView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorModel* new_qMRMLColorModel(QObject*  parent = 0)
    {
    return new qMRMLColorModel(parent);
    }
  void delete_qMRMLColorModel(qMRMLColorModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorPickerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorPickerWidget* new_qMRMLColorPickerWidget(QWidget*  parent = 0)
    {
    return new qMRMLColorPickerWidget(parent);
    }
  void delete_qMRMLColorPickerWidget(qMRMLColorPickerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorTableComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorTableComboBox* new_qMRMLColorTableComboBox(QWidget*  parent = 0)
    {
    return new qMRMLColorTableComboBox(parent);
    }
  void delete_qMRMLColorTableComboBox(qMRMLColorTableComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorTableView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorTableView* new_qMRMLColorTableView(QWidget*  parent = 0)
    {
    return new qMRMLColorTableView(parent);
    }
  void delete_qMRMLColorTableView(qMRMLColorTableView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLCoordinatesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLCoordinatesWidget* new_qMRMLCoordinatesWidget(QWidget*  parent = 0)
    {
    return new qMRMLCoordinatesWidget(parent);
    }
  void delete_qMRMLCoordinatesWidget(qMRMLCoordinatesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLDisplayNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLDisplayNodeWidget* new_qMRMLDisplayNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLDisplayNodeWidget(parent);
    }
  void delete_qMRMLDisplayNodeWidget(qMRMLDisplayNodeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLDisplayNodeViewComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLDisplayNodeViewComboBox* new_qMRMLDisplayNodeViewComboBox(QWidget*  parent = 0)
    {
    return new qMRMLDisplayNodeViewComboBox(parent);
    }
  void delete_qMRMLDisplayNodeViewComboBox(qMRMLDisplayNodeViewComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLLabelComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLLabelComboBox* new_qMRMLLabelComboBox(QWidget*  parent = 0)
    {
    return new qMRMLLabelComboBox(parent);
    }
  void delete_qMRMLLabelComboBox(qMRMLLabelComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLEventBrokerConnection : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLEventBrokerConnection* new_qMRMLEventBrokerConnection(QObject*  parent = 0)
    {
    return new qMRMLEventBrokerConnection(parent);
    }
  void delete_qMRMLEventBrokerConnection(qMRMLEventBrokerConnection* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLEventBrokerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLEventBrokerWidget* new_qMRMLEventBrokerWidget(QWidget*  parent = 0)
    {
    return new qMRMLEventBrokerWidget(parent);
    }
  void delete_qMRMLEventBrokerWidget(qMRMLEventBrokerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLEventLogger : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLEventLogger* new_qMRMLEventLogger(QObject*  parent = 0)
    {
    return new qMRMLEventLogger(parent);
    }
  void delete_qMRMLEventLogger(qMRMLEventLogger* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLEventLoggerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLEventLoggerWidget* new_qMRMLEventLoggerWidget(QWidget*  parent = 0)
    {
    return new qMRMLEventLoggerWidget(parent);
    }
  void delete_qMRMLEventLoggerWidget(qMRMLEventLoggerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLItemDelegate : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLItemDelegate* new_qMRMLItemDelegate(QObject*  parent = 0)
    {
    return new qMRMLItemDelegate(parent);
    }
  void delete_qMRMLItemDelegate(qMRMLItemDelegate* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLLayoutManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLLayoutManager* new_qMRMLLayoutManager(QObject*  parent = 0)
    {
    return new qMRMLLayoutManager(parent);
    }
  void delete_qMRMLLayoutManager(qMRMLLayoutManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLLayoutViewFactory : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLLayoutViewFactory* new_qMRMLLayoutViewFactory(QObject*  parent = 0)
    {
    return new qMRMLLayoutViewFactory(parent);
    }
  void delete_qMRMLLayoutViewFactory(qMRMLLayoutViewFactory* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLLayoutWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLLayoutWidget* new_qMRMLLayoutWidget(QWidget*  parent = 0)
    {
    return new qMRMLLayoutWidget(parent);
    }
  void delete_qMRMLLayoutWidget(qMRMLLayoutWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLLinearTransformSlider : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLLinearTransformSlider* new_qMRMLLinearTransformSlider(QWidget*  parent = 0)
    {
    return new qMRMLLinearTransformSlider(parent);
    }
  void delete_qMRMLLinearTransformSlider(qMRMLLinearTransformSlider* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLListWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLListWidget* new_qMRMLListWidget(QWidget*  parent = 0)
    {
    return new qMRMLListWidget(parent);
    }
  void delete_qMRMLListWidget(qMRMLListWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMatrixWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMatrixWidget* new_qMRMLMatrixWidget(QWidget*  parent = 0)
    {
    return new qMRMLMatrixWidget(parent);
    }
  void delete_qMRMLMatrixWidget(qMRMLMatrixWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLModelInfoWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLModelInfoWidget* new_qMRMLModelInfoWidget(QWidget*  parent = 0)
    {
    return new qMRMLModelInfoWidget(parent);
    }
  void delete_qMRMLModelInfoWidget(qMRMLModelInfoWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLNavigationView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLNavigationView* new_qMRMLNavigationView(QWidget*  parent = 0)
    {
    return new qMRMLNavigationView(parent);
    }
  void delete_qMRMLNavigationView(qMRMLNavigationView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLNodeAttributeTableView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLNodeAttributeTableView* new_qMRMLNodeAttributeTableView(QWidget*  parent = 0)
    {
    return new qMRMLNodeAttributeTableView(parent);
    }
  void delete_qMRMLNodeAttributeTableView(qMRMLNodeAttributeTableView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLNodeAttributeTableWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLNodeAttributeTableWidget* new_qMRMLNodeAttributeTableWidget(QWidget*  parent = 0)
    {
    return new qMRMLNodeAttributeTableWidget(parent);
    }
  void delete_qMRMLNodeAttributeTableWidget(qMRMLNodeAttributeTableWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLNodeComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLNodeComboBox* new_qMRMLNodeComboBox(QWidget*  parent = 0)
    {
    return new qMRMLNodeComboBox(parent);
    }
  void delete_qMRMLNodeComboBox(qMRMLNodeComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLNodeFactory : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLNodeFactory* new_qMRMLNodeFactory(QObject*  parent = 0)
    {
    return new qMRMLNodeFactory(parent);
    }
  void delete_qMRMLNodeFactory(qMRMLNodeFactory* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLPlotWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLPlotWidget* new_qMRMLPlotWidget(QWidget*  parent = 0)
    {
    return new qMRMLPlotWidget(parent);
    }
  void delete_qMRMLPlotWidget(qMRMLPlotWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLPlotView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLPlotView* new_qMRMLPlotView(QWidget*  parent = 0)
    {
    return new qMRMLPlotView(parent);
    }
  void delete_qMRMLPlotView(qMRMLPlotView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLPlotViewControllerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLPlotViewControllerWidget* new_qMRMLPlotViewControllerWidget(QWidget*  parent = 0)
    {
    return new qMRMLPlotViewControllerWidget(parent);
    }
  void delete_qMRMLPlotViewControllerWidget(qMRMLPlotViewControllerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLRangeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLRangeWidget* new_qMRMLRangeWidget(QWidget*  parent = 0)
    {
    return new qMRMLRangeWidget(parent);
    }
  void delete_qMRMLRangeWidget(qMRMLRangeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLROIWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLROIWidget* new_qMRMLROIWidget(QWidget*  parent = 0)
    {
    return new qMRMLROIWidget(parent);
    }
  void delete_qMRMLROIWidget(qMRMLROIWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLScalarInvariantComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLScalarInvariantComboBox* new_qMRMLScalarInvariantComboBox(QWidget*  parent = 0)
    {
    return new qMRMLScalarInvariantComboBox(parent);
    }
  void delete_qMRMLScalarInvariantComboBox(qMRMLScalarInvariantComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLScalarsDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLScalarsDisplayWidget* new_qMRMLScalarsDisplayWidget(QWidget*  parent = 0)
    {
    return new qMRMLScalarsDisplayWidget(parent);
    }
  void delete_qMRMLScalarsDisplayWidget(qMRMLScalarsDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneCategoryModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneCategoryModel* new_qMRMLSceneCategoryModel(QObject*  parent = 0)
    {
    return new qMRMLSceneCategoryModel(parent);
    }
  void delete_qMRMLSceneCategoryModel(qMRMLSceneCategoryModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneColorTableModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneColorTableModel* new_qMRMLSceneColorTableModel(QObject*  parent = 0)
    {
    return new qMRMLSceneColorTableModel(parent);
    }
  void delete_qMRMLSceneColorTableModel(qMRMLSceneColorTableModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneFactoryWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneFactoryWidget* new_qMRMLSceneFactoryWidget(QWidget*  parent = 0)
    {
    return new qMRMLSceneFactoryWidget(parent);
    }
  void delete_qMRMLSceneFactoryWidget(qMRMLSceneFactoryWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneModel* new_qMRMLSceneModel(QObject*  parent = 0)
    {
    return new qMRMLSceneModel(parent);
    }
  void delete_qMRMLSceneModel(qMRMLSceneModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneViewMenu : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneViewMenu* new_qMRMLSceneViewMenu(QWidget*  parent = 0)
    {
    return new qMRMLSceneViewMenu(parent);
    }
  void delete_qMRMLSceneViewMenu(qMRMLSceneViewMenu* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneTransformModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneTransformModel* new_qMRMLSceneTransformModel(QObject*  parent = 0)
    {
    return new qMRMLSceneTransformModel(parent);
    }
  void delete_qMRMLSceneTransformModel(qMRMLSceneTransformModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneHierarchyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneHierarchyModel* new_qMRMLSceneHierarchyModel(QObject*  parent = 0)
    {
    return new qMRMLSceneHierarchyModel(parent);
    }
  void delete_qMRMLSceneHierarchyModel(qMRMLSceneHierarchyModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSceneDisplayableModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSceneDisplayableModel* new_qMRMLSceneDisplayableModel(QObject*  parent = 0)
    {
    return new qMRMLSceneDisplayableModel(parent);
    }
  void delete_qMRMLSceneDisplayableModel(qMRMLSceneDisplayableModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLScreenShotDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLScreenShotDialog* new_qMRMLScreenShotDialog(QWidget*  parent = 0)
    {
    return new qMRMLScreenShotDialog(parent);
    }
  void delete_qMRMLScreenShotDialog(qMRMLScreenShotDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentSelectorWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentSelectorWidget* new_qMRMLSegmentSelectorWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentSelectorWidget(parent);
    }
  void delete_qMRMLSegmentSelectorWidget(qMRMLSegmentSelectorWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliceControllerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliceControllerWidget* new_qMRMLSliceControllerWidget(QWidget*  parent = 0)
    {
    return new qMRMLSliceControllerWidget(parent);
    }
  void delete_qMRMLSliceControllerWidget(qMRMLSliceControllerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliceInformationWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliceInformationWidget* new_qMRMLSliceInformationWidget(QWidget*  parent = 0)
    {
    return new qMRMLSliceInformationWidget(parent);
    }
  void delete_qMRMLSliceInformationWidget(qMRMLSliceInformationWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliceVerticalControllerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliceVerticalControllerWidget* new_qMRMLSliceVerticalControllerWidget(QWidget*  parent = 0)
    {
    return new qMRMLSliceVerticalControllerWidget(parent);
    }
  void delete_qMRMLSliceVerticalControllerWidget(qMRMLSliceVerticalControllerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliceView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliceView* new_qMRMLSliceView(QWidget*  parent = 0)
    {
    return new qMRMLSliceView(parent);
    }
  void delete_qMRMLSliceView(qMRMLSliceView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliceWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliceWidget* new_qMRMLSliceWidget(QWidget*  parent = 0)
    {
    return new qMRMLSliceWidget(parent);
    }
  void delete_qMRMLSliceWidget(qMRMLSliceWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSliderWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSliderWidget* new_qMRMLSliderWidget(QWidget*  parent = 0)
    {
    return new qMRMLSliderWidget(parent);
    }
  void delete_qMRMLSliderWidget(qMRMLSliderWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSortFilterHierarchyProxyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSortFilterHierarchyProxyModel* new_qMRMLSortFilterHierarchyProxyModel(QObject*  parent = 0)
    {
    return new qMRMLSortFilterHierarchyProxyModel(parent);
    }
  void delete_qMRMLSortFilterHierarchyProxyModel(qMRMLSortFilterHierarchyProxyModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSortFilterProxyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSortFilterProxyModel* new_qMRMLSortFilterProxyModel(QObject*  parent = 0)
    {
    return new qMRMLSortFilterProxyModel(parent);
    }
  void delete_qMRMLSortFilterProxyModel(qMRMLSortFilterProxyModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSpinBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSpinBox* new_qMRMLSpinBox(QWidget*  parent = 0)
    {
    return new qMRMLSpinBox(parent);
    }
  void delete_qMRMLSpinBox(qMRMLSpinBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTableModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTableModel* new_qMRMLTableModel(QObject*  parent = 0)
    {
    return new qMRMLTableModel(parent);
    }
  void delete_qMRMLTableModel(qMRMLTableModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTableView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTableView* new_qMRMLTableView(QWidget*  parent = 0)
    {
    return new qMRMLTableView(parent);
    }
  void delete_qMRMLTableView(qMRMLTableView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTableViewControllerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTableViewControllerWidget* new_qMRMLTableViewControllerWidget(QWidget*  parent = 0)
    {
    return new qMRMLTableViewControllerWidget(parent);
    }
  void delete_qMRMLTableViewControllerWidget(qMRMLTableViewControllerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTableWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTableWidget* new_qMRMLTableWidget(QWidget*  parent = 0)
    {
    return new qMRMLTableWidget(parent);
    }
  void delete_qMRMLTableWidget(qMRMLTableWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLThreeDView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLThreeDView* new_qMRMLThreeDView(QWidget*  parent = 0)
    {
    return new qMRMLThreeDView(parent);
    }
  void delete_qMRMLThreeDView(qMRMLThreeDView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLThreeDViewControllerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLThreeDViewControllerWidget* new_qMRMLThreeDViewControllerWidget(QWidget*  parent = 0)
    {
    return new qMRMLThreeDViewControllerWidget(parent);
    }
  void delete_qMRMLThreeDViewControllerWidget(qMRMLThreeDViewControllerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLThreeDViewInformationWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLThreeDViewInformationWidget* new_qMRMLThreeDViewInformationWidget(QWidget*  parent = 0)
    {
    return new qMRMLThreeDViewInformationWidget(parent);
    }
  void delete_qMRMLThreeDViewInformationWidget(qMRMLThreeDViewInformationWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLThreeDWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLThreeDWidget* new_qMRMLThreeDWidget(QWidget*  parent = 0)
    {
    return new qMRMLThreeDWidget(parent);
    }
  void delete_qMRMLThreeDWidget(qMRMLThreeDWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTransformSliders : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTransformSliders* new_qMRMLTransformSliders(QWidget*  parent = 0)
    {
    return new qMRMLTransformSliders(parent);
    }
  void delete_qMRMLTransformSliders(qMRMLTransformSliders* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTreeView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTreeView* new_qMRMLTreeView(QWidget*  parent = 0)
    {
    return new qMRMLTreeView(parent);
    }
  void delete_qMRMLTreeView(qMRMLTreeView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLUtils : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLUtils* new_qMRMLUtils(QObject*  parent = 0)
    {
    return new qMRMLUtils(parent);
    }
  void delete_qMRMLUtils(qMRMLUtils* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLViewControllerBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLViewControllerBar* new_qMRMLViewControllerBar(QWidget*  parent = 0)
    {
    return new qMRMLViewControllerBar(parent);
    }
  void delete_qMRMLViewControllerBar(qMRMLViewControllerBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLVolumeInfoWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLVolumeInfoWidget* new_qMRMLVolumeInfoWidget(QWidget*  parent = 0)
    {
    return new qMRMLVolumeInfoWidget(parent);
    }
  void delete_qMRMLVolumeInfoWidget(qMRMLVolumeInfoWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLVolumeThresholdWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLVolumeThresholdWidget* new_qMRMLVolumeThresholdWidget(QWidget*  parent = 0)
    {
    return new qMRMLVolumeThresholdWidget(parent);
    }
  void delete_qMRMLVolumeThresholdWidget(qMRMLVolumeThresholdWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLVolumeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLVolumeWidget* new_qMRMLVolumeWidget(QWidget*  parent = 0)
    {
    return new qMRMLVolumeWidget(parent);
    }
  void delete_qMRMLVolumeWidget(qMRMLVolumeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLWidget* new_qMRMLWidget(QWidget*  parent = 0)
    {
    return new qMRMLWidget(parent);
    }
  void delete_qMRMLWidget(qMRMLWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLWindowLevelWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLWindowLevelWidget* new_qMRMLWindowLevelWidget(QWidget*  parent = 0)
    {
    return new qMRMLWindowLevelWidget(parent);
    }
  void delete_qMRMLWindowLevelWidget(qMRMLWindowLevelWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLExpandingWebView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLExpandingWebView* new_qMRMLExpandingWebView(QWidget*  parent = 0)
    {
    return new qMRMLExpandingWebView(parent);
    }
  void delete_qMRMLExpandingWebView(qMRMLExpandingWebView* obj) { delete obj; }
};

#endif
