// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkSlicerTransformsModuleMRMLDisplayableManagerObjectFactory(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformsDisplayableManager2D(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformsDisplayableManager3D(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLinearTransformsDisplayableManager3D(PyObject *dict); }

static PyMethodDef PyvtkSlicerTransformsModuleMRMLDisplayableManagerPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkSlicerTransformsModuleMRMLDisplayableManagerPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkSlicerTransformsModuleMRMLDisplayableManagerPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkSlicerTransformsModuleMRMLDisplayableManagerPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkSlicerTransformsModuleMRMLDisplayableManagerPython(const char * /*unused*/); }

PyObject *real_initvtkSlicerTransformsModuleMRMLDisplayableManagerPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkSlicerTransformsModuleMRMLDisplayableManagerPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkSlicerTransformsModuleMRMLDisplayableManagerPython");
  }

  const char *depends[12] = {
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "MRMLLogicPython",
    "MRMLDisplayableManagerPython",
    "MRMLCLIPython",
    "vtkSlicerTransformsModuleLogicPython",
    "vtkSlicerMarkupsModuleMRMLPython",
    "qSlicerBaseQTCLIPython",
    "SlicerBaseLogicPython",
  };

  for (int i = 0; i < 12; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load vtkSlicerTransformsModuleMRMLDisplayableManagerPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for vtkSlicerTransformsModuleMRMLDisplayableManagerPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkSlicerTransformsModuleMRMLDisplayableManagerObjectFactory(d);
  PyVTKAddFile_vtkMRMLTransformsDisplayableManager2D(d);
  PyVTKAddFile_vtkMRMLTransformsDisplayableManager3D(d);
  PyVTKAddFile_vtkMRMLLinearTransformsDisplayableManager3D(d);

  vtkPythonUtil::AddModule("vtkSlicerTransformsModuleMRMLDisplayableManagerPython");

  return m;
}

