
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerSubjectHierarchyModuleWidgets.h"

void PythonQt_init_osm_qSlicerSubjectHierarchyModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qMRMLSubjectHierarchyModel::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSubjectHierarchyModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSortFilterSubjectHierarchyProxyModel::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSortFilterSubjectHierarchyProxyModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSubjectHierarchyTreeView::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSubjectHierarchyTreeView>);
  

  PythonQt::self()->registerClass(
  &qMRMLSubjectHierarchyComboBox::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSubjectHierarchyComboBox>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyPluginLogic::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyPluginLogic>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyPluginHandler::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyPluginHandler>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyDefaultPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyDefaultPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyCloneNodePlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyCloneNodePlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyParseLocalDataPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyParseLocalDataPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyRegisterPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyRegisterPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyFolderPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyFolderPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyOpacityPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyOpacityPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyViewContextMenuPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyViewContextMenuPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyVisibilityPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyVisibilityPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyExportPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyExportPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyExpandToDepthPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyExpandToDepthPlugin>);
  

  PythonQt::self()->registerClass(
  &qSlicerSubjectHierarchyScriptedPlugin::staticMetaObject, "qSlicerSubjectHierarchyModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSubjectHierarchyScriptedPlugin>);
  
}
