
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerSubjectHierarchyModuleWidgets_h
#define __osm_qSlicerSubjectHierarchyModuleWidgets_h

#include <QObject>
#include "qMRMLSubjectHierarchyModel.h"
#include "qMRMLSortFilterSubjectHierarchyProxyModel.h"
#include "qMRMLSubjectHierarchyTreeView.h"
#include "qMRMLSubjectHierarchyComboBox.h"
#include "qSlicerSubjectHierarchyPluginLogic.h"
#include "qSlicerSubjectHierarchyPluginHandler.h"
#include "qSlicerSubjectHierarchyDefaultPlugin.h"
#include "qSlicerSubjectHierarchyCloneNodePlugin.h"
#include "qSlicerSubjectHierarchyParseLocalDataPlugin.h"
#include "qSlicerSubjectHierarchyRegisterPlugin.h"
#include "qSlicerSubjectHierarchyFolderPlugin.h"
#include "qSlicerSubjectHierarchyOpacityPlugin.h"
#include "qSlicerSubjectHierarchyViewContextMenuPlugin.h"
#include "qSlicerSubjectHierarchyVisibilityPlugin.h"
#include "qSlicerSubjectHierarchyExportPlugin.h"
#include "qSlicerSubjectHierarchyExpandToDepthPlugin.h"
#include "qSlicerSubjectHierarchyScriptedPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSubjectHierarchyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSubjectHierarchyModel* new_qMRMLSubjectHierarchyModel(QObject*  parent = 0)
    {
    return new qMRMLSubjectHierarchyModel(parent);
    }
  void delete_qMRMLSubjectHierarchyModel(qMRMLSubjectHierarchyModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSortFilterSubjectHierarchyProxyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSortFilterSubjectHierarchyProxyModel* new_qMRMLSortFilterSubjectHierarchyProxyModel(QObject*  parent = 0)
    {
    return new qMRMLSortFilterSubjectHierarchyProxyModel(parent);
    }
  void delete_qMRMLSortFilterSubjectHierarchyProxyModel(qMRMLSortFilterSubjectHierarchyProxyModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSubjectHierarchyTreeView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSubjectHierarchyTreeView* new_qMRMLSubjectHierarchyTreeView(QWidget*  parent = 0)
    {
    return new qMRMLSubjectHierarchyTreeView(parent);
    }
  void delete_qMRMLSubjectHierarchyTreeView(qMRMLSubjectHierarchyTreeView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSubjectHierarchyComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSubjectHierarchyComboBox* new_qMRMLSubjectHierarchyComboBox(QWidget*  parent = 0)
    {
    return new qMRMLSubjectHierarchyComboBox(parent);
    }
  void delete_qMRMLSubjectHierarchyComboBox(qMRMLSubjectHierarchyComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyPluginLogic : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyPluginLogic* new_qSlicerSubjectHierarchyPluginLogic(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyPluginLogic(parent);
    }
  void delete_qSlicerSubjectHierarchyPluginLogic(qSlicerSubjectHierarchyPluginLogic* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyPluginHandler : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyPluginHandler* new_qSlicerSubjectHierarchyPluginHandler(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyPluginHandler(parent);
    }
  void delete_qSlicerSubjectHierarchyPluginHandler(qSlicerSubjectHierarchyPluginHandler* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyDefaultPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyDefaultPlugin* new_qSlicerSubjectHierarchyDefaultPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyDefaultPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyDefaultPlugin(qSlicerSubjectHierarchyDefaultPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyCloneNodePlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyCloneNodePlugin* new_qSlicerSubjectHierarchyCloneNodePlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyCloneNodePlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyCloneNodePlugin(qSlicerSubjectHierarchyCloneNodePlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyParseLocalDataPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyParseLocalDataPlugin* new_qSlicerSubjectHierarchyParseLocalDataPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyParseLocalDataPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyParseLocalDataPlugin(qSlicerSubjectHierarchyParseLocalDataPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyRegisterPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyRegisterPlugin* new_qSlicerSubjectHierarchyRegisterPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyRegisterPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyRegisterPlugin(qSlicerSubjectHierarchyRegisterPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyFolderPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyFolderPlugin* new_qSlicerSubjectHierarchyFolderPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyFolderPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyFolderPlugin(qSlicerSubjectHierarchyFolderPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyOpacityPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyOpacityPlugin* new_qSlicerSubjectHierarchyOpacityPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyOpacityPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyOpacityPlugin(qSlicerSubjectHierarchyOpacityPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyViewContextMenuPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyViewContextMenuPlugin* new_qSlicerSubjectHierarchyViewContextMenuPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyViewContextMenuPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyViewContextMenuPlugin(qSlicerSubjectHierarchyViewContextMenuPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyVisibilityPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyVisibilityPlugin* new_qSlicerSubjectHierarchyVisibilityPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyVisibilityPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyVisibilityPlugin(qSlicerSubjectHierarchyVisibilityPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyExportPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyExportPlugin* new_qSlicerSubjectHierarchyExportPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyExportPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyExportPlugin(qSlicerSubjectHierarchyExportPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyExpandToDepthPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyExpandToDepthPlugin* new_qSlicerSubjectHierarchyExpandToDepthPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyExpandToDepthPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyExpandToDepthPlugin(qSlicerSubjectHierarchyExpandToDepthPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyScriptedPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyScriptedPlugin* new_qSlicerSubjectHierarchyScriptedPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyScriptedPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyScriptedPlugin(qSlicerSubjectHierarchyScriptedPlugin* obj) { delete obj; }
};

#endif
