
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerMarkupsSubjectHierarchyPlugins_h
#define __osm_qSlicerMarkupsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyMarkupsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyMarkupsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyMarkupsPlugin* new_qSlicerSubjectHierarchyMarkupsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyMarkupsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyMarkupsPlugin(qSlicerSubjectHierarchyMarkupsPlugin* obj) { delete obj; }
};

#endif
