// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkSlicerSegmentationsModuleLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerSegmentationsModuleLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerSegmentationGeometryLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerSegmentationGeometryLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkImageGrowCutSegment(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkImageGrowCutSegment(PyObject *dict); }
extern "C" { void PyVTKAddFile_FibHeap(PyObject *dict); }

static PyMethodDef PyvtkSlicerSegmentationsModuleLogicPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkSlicerSegmentationsModuleLogicPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkSlicerSegmentationsModuleLogicPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkSlicerSegmentationsModuleLogicPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkSlicerSegmentationsModuleLogicPython(const char * /*unused*/); }

PyObject *real_initvtkSlicerSegmentationsModuleLogicPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkSlicerSegmentationsModuleLogicPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkSlicerSegmentationsModuleLogicPython");
  }

  const char *depends[14] = {
    "vtkSlicerSegmentationsModuleMRMLPython",
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "vtkSlicerSubjectHierarchyModuleLogicPython",
    "qSlicerBaseQTCLIPython",
    "MRMLCLIPython",
    "SlicerBaseLogicPython",
    "MRMLLogicPython",
    "MRMLDisplayableManagerPython",
    "vtkSlicerTerminologiesModuleLogicPython",
    "vtkSlicerMarkupsModuleMRMLPython",
  };

  for (int i = 0; i < 14; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load vtkSlicerSegmentationsModuleLogicPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for vtkSlicerSegmentationsModuleLogicPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkSlicerSegmentationsModuleLogic(d);
  PyVTKAddFile_vtkSlicerSegmentationsModuleLogic(d);
  PyVTKAddFile_vtkSlicerSegmentationGeometryLogic(d);
  PyVTKAddFile_vtkSlicerSegmentationGeometryLogic(d);
  PyVTKAddFile_vtkImageGrowCutSegment(d);
  PyVTKAddFile_vtkImageGrowCutSegment(d);
  PyVTKAddFile_FibHeap(d);

  vtkPythonUtil::AddModule("vtkSlicerSegmentationsModuleLogicPython");

  return m;
}

