
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osb_qSlicerBaseQTGUI_h
#define __osb_qSlicerBaseQTGUI_h

#include <QObject>
#include "qSlicerActionsDialog.h"
#include "qSlicerDataDialog.h"
#include "qSlicerDirectoryListView.h"
#include "qSlicerExportNodeDialog.h"
#include "qSlicerFileWriterOptionsWidget.h"
#include "qSlicerIOManager.h"
#include "qSlicerIOOptionsWidget.h"
#include "qSlicerLayoutManager.h"
#include "qSlicerModelsDialog.h"
#include "qSlicerModuleFactoryFilterModel.h"
#include "qSlicerModuleFinderDialog.h"
#include "qSlicerModulesListView.h"
#include "qSlicerModulesMenu.h"
#include "qSlicerModulePanel.h"
#include "qSlicerModuleSelectorToolBar.h"
#include "qSlicerMouseModeToolBar.h"
#include "qSlicerNodeWriterOptionsWidget.h"
#include "qSlicerSaveDataDialog.h"
#include "qSlicerSettingsCachePanel.h"
#include "qSlicerSettingsGeneralPanel.h"
#include "qSlicerSettingsModulesPanel.h"
#include "qSlicerSettingsStylesPanel.h"
#include "qSlicerSettingsViewsPanel.h"
#include "qSlicerSettingsDeveloperPanel.h"
#include "qSlicerSettingsUserInformationPanel.h"
#include "qSlicerViewersToolBar.h"
#include "qSlicerWidget.h"
#include "qSlicerSingletonViewFactory.h"
#include "qSlicerSettingsInternationalizationPanel.h"
#include "qSlicerWebPythonProxy.h"
#include "qSlicerWebDownloadWidget.h"
#include "qSlicerWebWidget.h"
#include "qSlicerScriptedLoadableModuleWidget.h"
#include "qSlicerScriptedLoadableModule.h"
#include "qSlicerScriptedFileDialog.h"
#include "qSlicerSettingsPythonPanel.h"
#include "qSlicerPythonManager.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerActionsDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerActionsDialog* new_qSlicerActionsDialog(QWidget*  parent = 0)
    {
    return new qSlicerActionsDialog(parent);
    }
  void delete_qSlicerActionsDialog(qSlicerActionsDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDataDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDataDialog* new_qSlicerDataDialog(QObject*  parent = 0)
    {
    return new qSlicerDataDialog(parent);
    }
  void delete_qSlicerDataDialog(qSlicerDataDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDirectoryListView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDirectoryListView* new_qSlicerDirectoryListView(QWidget*  parent = 0)
    {
    return new qSlicerDirectoryListView(parent);
    }
  void delete_qSlicerDirectoryListView(qSlicerDirectoryListView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerExportNodeDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerExportNodeDialog* new_qSlicerExportNodeDialog(QObject*  parent = 0)
    {
    return new qSlicerExportNodeDialog(parent);
    }
  void delete_qSlicerExportNodeDialog(qSlicerExportNodeDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerFileWriterOptionsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerFileWriterOptionsWidget* new_qSlicerFileWriterOptionsWidget(QWidget*  parent = 0)
    {
    return new qSlicerFileWriterOptionsWidget(parent);
    }
  void delete_qSlicerFileWriterOptionsWidget(qSlicerFileWriterOptionsWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerIOManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerIOManager* new_qSlicerIOManager(QObject*  parent = 0)
    {
    return new qSlicerIOManager(parent);
    }
  void delete_qSlicerIOManager(qSlicerIOManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerIOOptionsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerIOOptionsWidget* new_qSlicerIOOptionsWidget(QWidget*  parent = 0)
    {
    return new qSlicerIOOptionsWidget(parent);
    }
  void delete_qSlicerIOOptionsWidget(qSlicerIOOptionsWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerLayoutManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerLayoutManager* new_qSlicerLayoutManager(QWidget*  parent = 0)
    {
    return new qSlicerLayoutManager(parent);
    }
  void delete_qSlicerLayoutManager(qSlicerLayoutManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModelsDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModelsDialog* new_qSlicerModelsDialog(QObject*  parent = 0)
    {
    return new qSlicerModelsDialog(parent);
    }
  void delete_qSlicerModelsDialog(qSlicerModelsDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModuleFactoryFilterModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModuleFactoryFilterModel* new_qSlicerModuleFactoryFilterModel(QObject*  parent = 0)
    {
    return new qSlicerModuleFactoryFilterModel(parent);
    }
  void delete_qSlicerModuleFactoryFilterModel(qSlicerModuleFactoryFilterModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModuleFinderDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModuleFinderDialog* new_qSlicerModuleFinderDialog(QWidget*  parent = 0)
    {
    return new qSlicerModuleFinderDialog(parent);
    }
  void delete_qSlicerModuleFinderDialog(qSlicerModuleFinderDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModulesListView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModulesListView* new_qSlicerModulesListView(QWidget*  parent = 0)
    {
    return new qSlicerModulesListView(parent);
    }
  void delete_qSlicerModulesListView(qSlicerModulesListView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModulesMenu : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModulesMenu* new_qSlicerModulesMenu(QWidget*  parent = 0)
    {
    return new qSlicerModulesMenu(parent);
    }
  void delete_qSlicerModulesMenu(qSlicerModulesMenu* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModulePanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModulePanel* new_qSlicerModulePanel(QWidget*  parent = 0)
    {
    return new qSlicerModulePanel(parent);
    }
  void delete_qSlicerModulePanel(qSlicerModulePanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModuleSelectorToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModuleSelectorToolBar* new_qSlicerModuleSelectorToolBar(QWidget*  parent = 0)
    {
    return new qSlicerModuleSelectorToolBar(parent);
    }
  void delete_qSlicerModuleSelectorToolBar(qSlicerModuleSelectorToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerMouseModeToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerMouseModeToolBar* new_qSlicerMouseModeToolBar(QWidget*  parent = 0)
    {
    return new qSlicerMouseModeToolBar(parent);
    }
  void delete_qSlicerMouseModeToolBar(qSlicerMouseModeToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerNodeWriterOptionsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerNodeWriterOptionsWidget* new_qSlicerNodeWriterOptionsWidget(QWidget*  parent = 0)
    {
    return new qSlicerNodeWriterOptionsWidget(parent);
    }
  void delete_qSlicerNodeWriterOptionsWidget(qSlicerNodeWriterOptionsWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSaveDataDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSaveDataDialog* new_qSlicerSaveDataDialog(QObject*  parent = 0)
    {
    return new qSlicerSaveDataDialog(parent);
    }
  void delete_qSlicerSaveDataDialog(qSlicerSaveDataDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsCachePanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsCachePanel* new_qSlicerSettingsCachePanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsCachePanel(parent);
    }
  void delete_qSlicerSettingsCachePanel(qSlicerSettingsCachePanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsGeneralPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsGeneralPanel* new_qSlicerSettingsGeneralPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsGeneralPanel(parent);
    }
  void delete_qSlicerSettingsGeneralPanel(qSlicerSettingsGeneralPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsModulesPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsModulesPanel* new_qSlicerSettingsModulesPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsModulesPanel(parent);
    }
  void delete_qSlicerSettingsModulesPanel(qSlicerSettingsModulesPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsStylesPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsStylesPanel* new_qSlicerSettingsStylesPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsStylesPanel(parent);
    }
  void delete_qSlicerSettingsStylesPanel(qSlicerSettingsStylesPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsViewsPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsViewsPanel* new_qSlicerSettingsViewsPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsViewsPanel(parent);
    }
  void delete_qSlicerSettingsViewsPanel(qSlicerSettingsViewsPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsDeveloperPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsDeveloperPanel* new_qSlicerSettingsDeveloperPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsDeveloperPanel(parent);
    }
  void delete_qSlicerSettingsDeveloperPanel(qSlicerSettingsDeveloperPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsUserInformationPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsUserInformationPanel* new_qSlicerSettingsUserInformationPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsUserInformationPanel(parent);
    }
  void delete_qSlicerSettingsUserInformationPanel(qSlicerSettingsUserInformationPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerViewersToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerViewersToolBar* new_qSlicerViewersToolBar(QWidget*  parent = 0)
    {
    return new qSlicerViewersToolBar(parent);
    }
  void delete_qSlicerViewersToolBar(qSlicerViewersToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerWidget* new_qSlicerWidget(QWidget*  parent = 0)
    {
    return new qSlicerWidget(parent);
    }
  void delete_qSlicerWidget(qSlicerWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSingletonViewFactory : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSingletonViewFactory* new_qSlicerSingletonViewFactory(QObject*  parent = 0)
    {
    return new qSlicerSingletonViewFactory(parent);
    }
  void delete_qSlicerSingletonViewFactory(qSlicerSingletonViewFactory* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsInternationalizationPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsInternationalizationPanel* new_qSlicerSettingsInternationalizationPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsInternationalizationPanel(parent);
    }
  void delete_qSlicerSettingsInternationalizationPanel(qSlicerSettingsInternationalizationPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerWebPythonProxy : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerWebPythonProxy* new_qSlicerWebPythonProxy(QObject*  parent = 0)
    {
    return new qSlicerWebPythonProxy(parent);
    }
  void delete_qSlicerWebPythonProxy(qSlicerWebPythonProxy* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerWebDownloadWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerWebDownloadWidget* new_qSlicerWebDownloadWidget(QWidget*  parent = 0)
    {
    return new qSlicerWebDownloadWidget(parent);
    }
  void delete_qSlicerWebDownloadWidget(qSlicerWebDownloadWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerWebWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerWebWidget* new_qSlicerWebWidget(QWidget*  parent = 0)
    {
    return new qSlicerWebWidget(parent);
    }
  void delete_qSlicerWebWidget(qSlicerWebWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScriptedLoadableModuleWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScriptedLoadableModuleWidget* new_qSlicerScriptedLoadableModuleWidget(QWidget*  parent = 0)
    {
    return new qSlicerScriptedLoadableModuleWidget(parent);
    }
  void delete_qSlicerScriptedLoadableModuleWidget(qSlicerScriptedLoadableModuleWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScriptedLoadableModule : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScriptedLoadableModule* new_qSlicerScriptedLoadableModule(QObject*  parent = 0)
    {
    return new qSlicerScriptedLoadableModule(parent);
    }
  void delete_qSlicerScriptedLoadableModule(qSlicerScriptedLoadableModule* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScriptedFileDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScriptedFileDialog* new_qSlicerScriptedFileDialog(QObject*  parent = 0)
    {
    return new qSlicerScriptedFileDialog(parent);
    }
  void delete_qSlicerScriptedFileDialog(qSlicerScriptedFileDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSettingsPythonPanel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSettingsPythonPanel* new_qSlicerSettingsPythonPanel(QWidget*  parent = 0)
    {
    return new qSlicerSettingsPythonPanel(parent);
    }
  void delete_qSlicerSettingsPythonPanel(qSlicerSettingsPythonPanel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerPythonManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerPythonManager* new_qSlicerPythonManager(QObject*  parent = 0)
    {
    return new qSlicerPythonManager(parent);
    }
  void delete_qSlicerPythonManager(qSlicerPythonManager* obj) { delete obj; }
};

#endif
