
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osb_qSlicerBaseQTGUI.h"

void PythonQt_init_osb_qSlicerBaseQTGUI(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerActionsDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerActionsDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerDataDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDataDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerDirectoryListView::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDirectoryListView>);
  

  PythonQt::self()->registerClass(
  &qSlicerExportNodeDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerExportNodeDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerFileWriterOptionsWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerFileWriterOptionsWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerIOManager::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerIOManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerIOOptionsWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerIOOptionsWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerLayoutManager::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerLayoutManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerModelsDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModelsDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerModuleFactoryFilterModel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModuleFactoryFilterModel>);
  

  PythonQt::self()->registerClass(
  &qSlicerModuleFinderDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModuleFinderDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerModulesListView::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModulesListView>);
  

  PythonQt::self()->registerClass(
  &qSlicerModulesMenu::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModulesMenu>);
  

  PythonQt::self()->registerClass(
  &qSlicerModulePanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModulePanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerModuleSelectorToolBar::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModuleSelectorToolBar>);
  

  PythonQt::self()->registerClass(
  &qSlicerMouseModeToolBar::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerMouseModeToolBar>);
  

  PythonQt::self()->registerClass(
  &qSlicerNodeWriterOptionsWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerNodeWriterOptionsWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerSaveDataDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSaveDataDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsCachePanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsCachePanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsGeneralPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsGeneralPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsModulesPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsModulesPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsStylesPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsStylesPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsViewsPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsViewsPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsDeveloperPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsDeveloperPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsUserInformationPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsUserInformationPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerViewersToolBar::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerViewersToolBar>);
  

  PythonQt::self()->registerClass(
  &qSlicerWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerSingletonViewFactory::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSingletonViewFactory>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsInternationalizationPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsInternationalizationPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerWebPythonProxy::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerWebPythonProxy>);
  

  PythonQt::self()->registerClass(
  &qSlicerWebDownloadWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerWebDownloadWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerWebWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerWebWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerScriptedLoadableModuleWidget::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScriptedLoadableModuleWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerScriptedLoadableModule::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScriptedLoadableModule>);
  

  PythonQt::self()->registerClass(
  &qSlicerScriptedFileDialog::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScriptedFileDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerSettingsPythonPanel::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSettingsPythonPanel>);
  

  PythonQt::self()->registerClass(
  &qSlicerPythonManager::staticMetaObject, "qSlicerBaseQTGUI",
  PythonQtCreateObject<PythonQtWrapper_qSlicerPythonManager>);
  
}
