
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerDICOMLibModuleWidgets.h"

void PythonQt_init_osm_qSlicerDICOMLibModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerDICOMExportDialog::staticMetaObject, "qSlicerDICOMLibModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDICOMExportDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerDICOMLoadable::staticMetaObject, "qSlicerDICOMLibModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDICOMLoadable>);
  

  PythonQt::self()->registerClass(
  &qSlicerDICOMExportable::staticMetaObject, "qSlicerDICOMLibModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDICOMExportable>);
  

  PythonQt::self()->registerClass(
  &qSlicerDICOMTagEditorWidget::staticMetaObject, "qSlicerDICOMLibModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDICOMTagEditorWidget>);
  
}
