
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerDICOMLibModuleWidgets_h
#define __osm_qSlicerDICOMLibModuleWidgets_h

#include <QObject>
#include "qSlicerDICOMExportDialog.h"
#include "qSlicerDICOMLoadable.h"
#include "qSlicerDICOMExportable.h"
#include "qSlicerDICOMTagEditorWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDICOMExportDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDICOMExportDialog* new_qSlicerDICOMExportDialog(QObject*  parent = 0)
    {
    return new qSlicerDICOMExportDialog(parent);
    }
  void delete_qSlicerDICOMExportDialog(qSlicerDICOMExportDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDICOMLoadable : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDICOMLoadable* new_qSlicerDICOMLoadable(QObject*  parent = 0)
    {
    return new qSlicerDICOMLoadable(parent);
    }
  void delete_qSlicerDICOMLoadable(qSlicerDICOMLoadable* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDICOMExportable : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDICOMExportable* new_qSlicerDICOMExportable(QObject*  parent = 0)
    {
    return new qSlicerDICOMExportable(parent);
    }
  void delete_qSlicerDICOMExportable(qSlicerDICOMExportable* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDICOMTagEditorWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDICOMTagEditorWidget* new_qSlicerDICOMTagEditorWidget(QWidget*  parent = 0)
    {
    return new qSlicerDICOMTagEditorWidget(parent);
    }
  void delete_qSlicerDICOMTagEditorWidget(qSlicerDICOMTagEditorWidget* obj) { delete obj; }
};

#endif
