# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Loadable/VolumeRendering/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[qMRMLVolumePropertyNodeWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "qMRMLVolumePropertyNodeWidgetTest1")
set_tests_properties([=[qMRMLVolumePropertyNodeWidgetTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;60;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qSlicerPresetComboBoxTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "qSlicerPresetComboBoxTest")
set_tests_properties([=[qSlicerPresetComboBoxTest]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;61;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qSlicerVolumeRenderingModuleWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "qSlicerVolumeRenderingModuleWidgetTest1")
set_tests_properties([=[qSlicerVolumeRenderingModuleWidgetTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;62;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qSlicerVolumeRenderingModuleWidgetTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "qSlicerVolumeRenderingModuleWidgetTest2" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[qSlicerVolumeRenderingModuleWidgetTest2]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;63;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLShaderPropertyStorageNodeTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "vtkMRMLShaderPropertyStorageNodeTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary")
set_tests_properties([=[vtkMRMLShaderPropertyStorageNodeTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;64;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLVolumePropertyNodeTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "vtkMRMLVolumePropertyNodeTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/../Data/Input/volRender.mrml")
set_tests_properties([=[vtkMRMLVolumePropertyNodeTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;65;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLVolumePropertyStorageNodeTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "vtkMRMLVolumePropertyStorageNodeTest1")
set_tests_properties([=[vtkMRMLVolumePropertyStorageNodeTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;66;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLVolumeRenderingDisplayableManagerTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "vtkMRMLVolumeRenderingDisplayableManagerTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/share/MINS-5.6/qt-loadable-modules/VolumeRendering")
set_tests_properties([=[vtkMRMLVolumeRenderingDisplayableManagerTest1]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;67;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLVolumeRenderingMultiVolumeTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumeRenderingModuleCxxTests" "vtkMRMLVolumeRenderingMultiVolumeTest")
set_tests_properties([=[vtkMRMLVolumeRenderingMultiVolumeTest]=] PROPERTIES  LABELS "qSlicerVolumeRenderingModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;68;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Testing/Cxx/CMakeLists.txt;0;")
