
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerMarkupsModuleWidgets_h
#define __osm_qSlicerMarkupsModuleWidgets_h

#include <QObject>
#include "qMRMLMarkupsDisplayNodeWidget.h"
#include "qMRMLMarkupsFiducialProjectionPropertyWidget.h"
#include "qMRMLMarkupsInteractionHandleWidget.h"
#include "qMRMLMarkupsToolBar.h"
#include "qMRMLMarkupsPlaneWidget.h"
#include "qMRMLMarkupsROIWidget.h"
#include "qMRMLMarkupsAngleMeasurementsWidget.h"
#include "qMRMLMarkupsCurveSettingsWidget.h"
#include "qMRMLMarkupsOptionsWidgetsFactory.h"
#include "qSlicerMarkupsPlaceWidget.h"
#include "qSlicerSimpleMarkupsWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsDisplayNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsDisplayNodeWidget* new_qMRMLMarkupsDisplayNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLMarkupsDisplayNodeWidget(parent);
    }
  void delete_qMRMLMarkupsDisplayNodeWidget(qMRMLMarkupsDisplayNodeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsFiducialProjectionPropertyWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsFiducialProjectionPropertyWidget* new_qMRMLMarkupsFiducialProjectionPropertyWidget(QWidget*  parent = 0)
    {
    return new qMRMLMarkupsFiducialProjectionPropertyWidget(parent);
    }
  void delete_qMRMLMarkupsFiducialProjectionPropertyWidget(qMRMLMarkupsFiducialProjectionPropertyWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsInteractionHandleWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsInteractionHandleWidget* new_qMRMLMarkupsInteractionHandleWidget(QWidget*  parent = 0)
    {
    return new qMRMLMarkupsInteractionHandleWidget(parent);
    }
  void delete_qMRMLMarkupsInteractionHandleWidget(qMRMLMarkupsInteractionHandleWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsToolBar* new_qMRMLMarkupsToolBar(QWidget*  parent = 0)
    {
    return new qMRMLMarkupsToolBar(parent);
    }
  void delete_qMRMLMarkupsToolBar(qMRMLMarkupsToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsPlaneWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsPlaneWidget* new_qMRMLMarkupsPlaneWidget()
    {
    return new qMRMLMarkupsPlaneWidget();
    }
  void delete_qMRMLMarkupsPlaneWidget(qMRMLMarkupsPlaneWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsROIWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsROIWidget* new_qMRMLMarkupsROIWidget()
    {
    return new qMRMLMarkupsROIWidget();
    }
  void delete_qMRMLMarkupsROIWidget(qMRMLMarkupsROIWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsAngleMeasurementsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsAngleMeasurementsWidget* new_qMRMLMarkupsAngleMeasurementsWidget()
    {
    return new qMRMLMarkupsAngleMeasurementsWidget();
    }
  void delete_qMRMLMarkupsAngleMeasurementsWidget(qMRMLMarkupsAngleMeasurementsWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsCurveSettingsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsCurveSettingsWidget* new_qMRMLMarkupsCurveSettingsWidget()
    {
    return new qMRMLMarkupsCurveSettingsWidget();
    }
  void delete_qMRMLMarkupsCurveSettingsWidget(qMRMLMarkupsCurveSettingsWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLMarkupsOptionsWidgetsFactory : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLMarkupsOptionsWidgetsFactory* new_qMRMLMarkupsOptionsWidgetsFactory(QObject*  parent = 0)
    {
    return new qMRMLMarkupsOptionsWidgetsFactory(parent);
    }
  void delete_qMRMLMarkupsOptionsWidgetsFactory(qMRMLMarkupsOptionsWidgetsFactory* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerMarkupsPlaceWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerMarkupsPlaceWidget* new_qSlicerMarkupsPlaceWidget(QWidget*  parent = 0)
    {
    return new qSlicerMarkupsPlaceWidget(parent);
    }
  void delete_qSlicerMarkupsPlaceWidget(qSlicerMarkupsPlaceWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSimpleMarkupsWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSimpleMarkupsWidget* new_qSlicerSimpleMarkupsWidget(QWidget*  parent = 0)
    {
    return new qSlicerSimpleMarkupsWidget(parent);
    }
  void delete_qSlicerSimpleMarkupsWidget(qSlicerSimpleMarkupsWidget* obj) { delete obj; }
};

#endif
