
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerMarkupsModuleWidgets.h"

void PythonQt_init_osm_qSlicerMarkupsModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qMRMLMarkupsDisplayNodeWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsDisplayNodeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsFiducialProjectionPropertyWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsFiducialProjectionPropertyWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsInteractionHandleWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsInteractionHandleWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsToolBar::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsToolBar>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsPlaneWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsPlaneWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsROIWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsROIWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsAngleMeasurementsWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsAngleMeasurementsWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsCurveSettingsWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsCurveSettingsWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLMarkupsOptionsWidgetsFactory::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLMarkupsOptionsWidgetsFactory>);
  

  PythonQt::self()->registerClass(
  &qSlicerMarkupsPlaceWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerMarkupsPlaceWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerSimpleMarkupsWidget::staticMetaObject, "qSlicerMarkupsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSimpleMarkupsWidget>);
  
}
