// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkSlicerModelsLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerModelsLogic(PyObject *dict); }

static PyMethodDef PyvtkSlicerModelsModuleLogicPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkSlicerModelsModuleLogicPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkSlicerModelsModuleLogicPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkSlicerModelsModuleLogicPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkSlicerModelsModuleLogicPython(const char * /*unused*/); }

PyObject *real_initvtkSlicerModelsModuleLogicPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkSlicerModelsModuleLogicPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkSlicerModelsModuleLogicPython");
  }

  const char *depends[10] = {
    "qSlicerBaseQTCLIPython",
    "MRMLCLIPython",
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "SlicerBaseLogicPython",
    "MRMLLogicPython",
    "MRMLDisplayableManagerPython",
  };

  for (int i = 0; i < 10; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load vtkSlicerModelsModuleLogicPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for vtkSlicerModelsModuleLogicPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkSlicerModelsLogic(d);
  PyVTKAddFile_vtkSlicerModelsLogic(d);

  vtkPythonUtil::AddModule("vtkSlicerModelsModuleLogicPython");

  return m;
}

