
# Generate compile_Slicer_python_scripts.py
file(WRITE "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/compile_Slicer_python_scripts.py" "
from __future__ import print_function

#
# Generated by ctkMacroCompilePythonScript CMake macro
#

#
# Copied function 'compileall.compile_file' introduced in python 2.7 so that code compiled
# using python 2.6 works.
#
# This version of the function has been copied from:
#   https://github.com/jonashaag/cpython/blob/ce5e5df0c9d8098da05dee26e12ffe2aa331889e/Lib/compileall.py#L61-111
#

import os
import sys
import py_compile
import struct
magic = None
if sys.version_info.major>= 3:
    import importlib
    magic = importlib.util.MAGIC_NUMBER
else:
    import imp
    magic = imp.get_magic()

def ctk_compile_file(fullname, ddir=None, force=0, rx=None, quiet=0):
    \"\"\"Byte-compile one file.

    Arguments (only fullname is required):

    fullname:  the file to byte-compile
    ddir:      if given, the directory name compiled in to the
               byte-code file.
    force:     if 1, force compilation, even if timestamps are up-to-date
    quiet:     if 1, be quiet during compilation
    \"\"\"
    success = 1
    name = os.path.basename(fullname)
    if ddir is not None:
        dfile = os.path.join(ddir, name)
    else:
        dfile = None
    if rx is not None:
        mo = rx.search(fullname)
        if mo:
            return success
    if os.path.isfile(fullname):
        head, tail = name[:-3], name[-3:]
        if tail == '.py':
            if not force:
                try:
                    mtime = int(os.stat(fullname).st_mtime)
                    expect = struct.pack('<4sl', magic, mtime)
                    cfile = fullname + (__debug__ and 'c' or 'o')
                    with open(cfile, 'rb') as chandle:
                        actual = chandle.read(8)
                    if expect == actual:
                        return success
                except IOError:
                    pass
            if not quiet:
                print('Compiling', fullname, '...')
            try:
                ok = py_compile.compile(fullname, None, dfile, True)
            except py_compile.PyCompileError as err:
                if quiet:
                    print('Compiling', fullname, '...')
                print(err.msg)
                success = 0
            except IOError as e:
                print('Sorry', e)
                success = 0
            else:
                if ok == 0:
                    success = 0
    return success

# Based on paraview/VTK/Wrapping/Python/compile_all_vtk.py.in


ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/mrmlDisplayableManager/vtkScriptedExampleDisplayableManager.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/i18n.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/logic.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/default.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/guiCreation.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/guiConnectors.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/parameterInfo.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/parameterPack.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/serializers.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/types.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/util.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/validators.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/parameterNodeWrapper/wrapper.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/ScriptedLoadableModule.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/slicerqt.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/testing.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/util.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/mrml.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/vtkAddon.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/vtkITK.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/vtkSegmentationCore.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/vtkTeem.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/cli.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/Python/slicer/kits.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/AbstractScriptedSubjectHierarchyPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/parameterNodeWrapper/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/parameterNodeWrapper/guiConnectors.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/ColorLegendSelfTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/AddManyMarkupsFiducialTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/NeurosurgicalPlanningTutorialMarkupsSelfTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/MarkupsInCompareViewersSelfTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/MarkupsInViewsSelfTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/PluggableMarkupsSelfTest.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorLabelEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorPaintEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorDrawEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorFillBetweenSlicesEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorGrowFromSeedsEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorHollowEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorIslandsEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorLevelTracingEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorLogicalEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorMarginEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorMaskVolumeEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorSmoothingEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditorEffects/SegmentEditorThresholdEffect.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/CropVolumeSequence.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/ImportItkSnapLabel.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/ScreenCapture.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/SegmentEditorSubjectHierarchyPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentEditor.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SubjectHierarchyPlugins/SegmentStatisticsSubjectHierarchyPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatisticsPlugins/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatisticsPlugins/SegmentStatisticsPluginBase.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatisticsPlugins/LabelmapSegmentStatisticsPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatisticsPlugins/ScalarVolumeSegmentStatisticsPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatisticsPlugins/ClosedSurfaceSegmentStatisticsPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SegmentStatistics.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SelfTests.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServer.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServerLib/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServerLib/BaseRequestHandler.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServerLib/DICOMRequestHandler.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServerLib/SlicerRequestHandler.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/WebServerLib/StaticPagesRequestHandler.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOM.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/__init__.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMBrowser.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMExportScalarVolume.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMExportScene.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMPluginSelector.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMProcesses.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMRecentActivityWidget.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMSendDialog.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMLib/DICOMUtils.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMEnhancedUSVolumePlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMGeAbusPlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMImageSequencePlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMScalarVolumePlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMVolumeSequencePlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMSlicerDataBundlePlugin.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/DICOMPatcher.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/Home.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/Resources/HomeResources.py', force=1)
ctk_compile_file('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules/SlicerCustomAppUtilities/__init__.py', force=1)
file = open('/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/python_compile_Slicer_complete', 'w')
file.write('Done')
")

set(ENV{PYTHONPATH} "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/CMakeFiles")

if(WIN32)
  set(ENV{PATH} "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/python-install/lib;$ENV{PATH}")
elseif(APPLE)
  set(ENV{DYLD_LIBRARY_PATH} "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/python-install/lib:$ENV{DYLD_LIBRARY_PATH}")
else()
  set(ENV{LD_LIBRARY_PATH} "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/python-install/lib:$ENV{LD_LIBRARY_PATH}")
endif()

execute_process(
  COMMAND "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/python-install/bin/PythonSlicer" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/compile_Slicer_python_scripts.py"
  RESULT_VARIABLE result_var
  )
if(NOT result_var STREQUAL 0)
  message(FATAL_ERROR "Failed to compile python scripts: Slicer ")
endif()
