
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerVolumeRenderingSubjectHierarchyPlugins_h
#define __osm_qSlicerVolumeRenderingSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyVolumeRenderingPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyVolumeRenderingPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyVolumeRenderingPlugin* new_qSlicerSubjectHierarchyVolumeRenderingPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyVolumeRenderingPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyVolumeRenderingPlugin(qSlicerSubjectHierarchyVolumeRenderingPlugin* obj) { delete obj; }
};

#endif
