
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerVolumeRenderingModuleWidgets_h
#define __osm_qSlicerVolumeRenderingModuleWidgets_h

#include <QObject>
#include "qSlicerCPURayCastVolumeRenderingPropertiesWidget.h"
#include "qSlicerGPURayCastVolumeRenderingPropertiesWidget.h"
#include "qSlicerMultiVolumeRenderingPropertiesWidget.h"
#include "qSlicerPresetComboBox.h"
#include "qSlicerVolumeRenderingModuleWidget.h"
#include "qSlicerVolumeRenderingPropertiesWidget.h"
#include "qSlicerVolumeRenderingPresetComboBox.h"
#include "qMRMLVolumePropertyNodeWidget.h"
#include "qSlicerGPUMemoryComboBox.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerCPURayCastVolumeRenderingPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerCPURayCastVolumeRenderingPropertiesWidget* new_qSlicerCPURayCastVolumeRenderingPropertiesWidget(QWidget*  parent = 0)
    {
    return new qSlicerCPURayCastVolumeRenderingPropertiesWidget(parent);
    }
  void delete_qSlicerCPURayCastVolumeRenderingPropertiesWidget(qSlicerCPURayCastVolumeRenderingPropertiesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerGPURayCastVolumeRenderingPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerGPURayCastVolumeRenderingPropertiesWidget* new_qSlicerGPURayCastVolumeRenderingPropertiesWidget(QWidget*  parent = 0)
    {
    return new qSlicerGPURayCastVolumeRenderingPropertiesWidget(parent);
    }
  void delete_qSlicerGPURayCastVolumeRenderingPropertiesWidget(qSlicerGPURayCastVolumeRenderingPropertiesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerMultiVolumeRenderingPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerMultiVolumeRenderingPropertiesWidget* new_qSlicerMultiVolumeRenderingPropertiesWidget(QWidget*  parent = 0)
    {
    return new qSlicerMultiVolumeRenderingPropertiesWidget(parent);
    }
  void delete_qSlicerMultiVolumeRenderingPropertiesWidget(qSlicerMultiVolumeRenderingPropertiesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerPresetComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerPresetComboBox* new_qSlicerPresetComboBox(QWidget*  parent = 0)
    {
    return new qSlicerPresetComboBox(parent);
    }
  void delete_qSlicerPresetComboBox(qSlicerPresetComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerVolumeRenderingModuleWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerVolumeRenderingModuleWidget* new_qSlicerVolumeRenderingModuleWidget(QWidget*  parent = 0)
    {
    return new qSlicerVolumeRenderingModuleWidget(parent);
    }
  void delete_qSlicerVolumeRenderingModuleWidget(qSlicerVolumeRenderingModuleWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerVolumeRenderingPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerVolumeRenderingPropertiesWidget* new_qSlicerVolumeRenderingPropertiesWidget(QWidget*  parent = 0)
    {
    return new qSlicerVolumeRenderingPropertiesWidget(parent);
    }
  void delete_qSlicerVolumeRenderingPropertiesWidget(qSlicerVolumeRenderingPropertiesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerVolumeRenderingPresetComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerVolumeRenderingPresetComboBox* new_qSlicerVolumeRenderingPresetComboBox(QWidget*  parent = 0)
    {
    return new qSlicerVolumeRenderingPresetComboBox(parent);
    }
  void delete_qSlicerVolumeRenderingPresetComboBox(qSlicerVolumeRenderingPresetComboBox* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLVolumePropertyNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLVolumePropertyNodeWidget* new_qMRMLVolumePropertyNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLVolumePropertyNodeWidget(parent);
    }
  void delete_qMRMLVolumePropertyNodeWidget(qMRMLVolumePropertyNodeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerGPUMemoryComboBox : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerGPUMemoryComboBox* new_qSlicerGPUMemoryComboBox(QWidget*  parent = 0)
    {
    return new qSlicerGPUMemoryComboBox(parent);
    }
  void delete_qSlicerGPUMemoryComboBox(qSlicerGPUMemoryComboBox* obj) { delete obj; }
};

#endif
