
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerVolumeRenderingModuleWidgets.h"

void PythonQt_init_osm_qSlicerVolumeRenderingModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerCPURayCastVolumeRenderingPropertiesWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerCPURayCastVolumeRenderingPropertiesWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerGPURayCastVolumeRenderingPropertiesWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerGPURayCastVolumeRenderingPropertiesWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerMultiVolumeRenderingPropertiesWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerMultiVolumeRenderingPropertiesWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerPresetComboBox::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerPresetComboBox>);
  

  PythonQt::self()->registerClass(
  &qSlicerVolumeRenderingModuleWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerVolumeRenderingModuleWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerVolumeRenderingPropertiesWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerVolumeRenderingPropertiesWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerVolumeRenderingPresetComboBox::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerVolumeRenderingPresetComboBox>);
  

  PythonQt::self()->registerClass(
  &qMRMLVolumePropertyNodeWidget::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLVolumePropertyNodeWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerGPUMemoryComboBox::staticMetaObject, "qSlicerVolumeRenderingModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerGPUMemoryComboBox>);
  
}
