
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerPlotsSubjectHierarchyPlugins_h
#define __osm_qSlicerPlotsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyPlotsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyPlotsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyPlotsPlugin* new_qSlicerSubjectHierarchyPlotsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyPlotsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyPlotsPlugin(qSlicerSubjectHierarchyPlotsPlugin* obj) { delete obj; }
};

#endif
