
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerColorsSubjectHierarchyPlugins_h
#define __osm_qSlicerColorsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyColorLegendPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyColorLegendPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyColorLegendPlugin* new_qSlicerSubjectHierarchyColorLegendPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyColorLegendPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyColorLegendPlugin(qSlicerSubjectHierarchyColorLegendPlugin* obj) { delete obj; }
};

#endif
