# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/QTApp/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Base/QTApp/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[qSlicerAboutDialogTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerBaseQTAppCxxTests" "qSlicerAboutDialogTest1")
set_tests_properties([=[qSlicerAboutDialogTest1]=] PROPERTIES  LABELS "qSlicerBaseQTApp" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/QTApp/Testing/Cxx/CMakeLists.txt;24;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/QTApp/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qSlicerErrorReportDialogTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerBaseQTAppCxxTests" "qSlicerErrorReportDialogTest1")
set_tests_properties([=[qSlicerErrorReportDialogTest1]=] PROPERTIES  LABELS "qSlicerBaseQTApp" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/QTApp/Testing/Cxx/CMakeLists.txt;25;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/QTApp/Testing/Cxx/CMakeLists.txt;0;")
