# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/ImportItkSnapLabel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[py_nomainwindow_qSlicerImportItkSnapLabelModuleGenericTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--no-main-window" "--disable-cli-modules" "--additional-module-path" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/ImportItkSnapLabel', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel'], 'qSlicerImportItkSnapLabelModuleGenericTest')")
set_tests_properties([=[py_nomainwindow_qSlicerImportItkSnapLabelModuleGenericTest]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroBuildScriptedModule.cmake;114;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel/CMakeLists.txt;14;slicerMacroBuildScriptedModule;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel/CMakeLists.txt;0;")
add_test([=[py_ImportItkSnapLabel]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/ImportItkSnapLabel', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel'], 'ImportItkSnapLabel')")
set_tests_properties([=[py_ImportItkSnapLabel]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel/CMakeLists.txt;26;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/ImportItkSnapLabel/CMakeLists.txt;0;")
