
set(Slicer_CMAKE_DIR "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake")
set(Slicer_BINARY_DIR "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build")
set(Slicer_OS "linux")
set(Slicer_ARCHITECTURE "amd64")
set(Slicer_VERSION_FULL "5.6.2-2024-04-05")
set(SLICER_PACKAGE_MANAGER_CLIENT_EXECUTABLE "SLICER_PACKAGE_MANAGER_CLIENT_EXECUTABLE-NOTDEFINED")
set(SLICER_PACKAGE_MANAGER_URL "SLICER_PACKAGE_MANAGER_URL-NOTDEFINED")
set(SLICER_PACKAGE_MANAGER_API_KEY "SLICER_PACKAGE_MANAGER_API_KEY-NOTDEFINED")
set(CTEST_MODEL "Experimental")
set(CTEST_MODEL "Experimental")
set(Slicer_REVISION "32448")
set(Slicer_WC_LAST_CHANGED_DATE "2024-04-05 00:00:56 -0400")
set(Slicer_WC_URL "https://github.com/Slicer/Slicer")