
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerVolumesSubjectHierarchyPlugins_h
#define __osm_qSlicerVolumesSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyVolumesPlugin.h"
#include "qSlicerSubjectHierarchyLabelMapsPlugin.h"
#include "qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyVolumesPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyVolumesPlugin* new_qSlicerSubjectHierarchyVolumesPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyVolumesPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyVolumesPlugin(qSlicerSubjectHierarchyVolumesPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyLabelMapsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyLabelMapsPlugin* new_qSlicerSubjectHierarchyLabelMapsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyLabelMapsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyLabelMapsPlugin(qSlicerSubjectHierarchyLabelMapsPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin* new_qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin(qSlicerSubjectHierarchyDiffusionTensorVolumesPlugin* obj) { delete obj; }
};

#endif
