# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Core/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[qSlicerEventBrokerModuleGenericTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModulesCoreCxxTests" "qSlicerEventBrokerModuleGenericTest")
set_tests_properties([=[qSlicerEventBrokerModuleGenericTest]=] PROPERTIES  LABELS "qSlicerModulesCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;32;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;0;")
add_test([=[qSlicerEventBrokerModuleWidgetGenericTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModulesCoreCxxTests" "qSlicerEventBrokerModuleWidgetGenericTest")
set_tests_properties([=[qSlicerEventBrokerModuleWidgetGenericTest]=] PROPERTIES  LABELS "qSlicerModulesCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;32;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;0;")
add_test([=[qSlicerCoreModuleTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModulesCoreCxxTests" "qSlicerCoreModuleTest1")
set_tests_properties([=[qSlicerCoreModuleTest1]=] PROPERTIES  LABELS "qSlicerModulesCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;34;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;0;")
add_test([=[qSlicerCoreModuleFactoryTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModulesCoreCxxTests" "qSlicerCoreModuleFactoryTest1")
set_tests_properties([=[qSlicerCoreModuleFactoryTest1]=] PROPERTIES  LABELS "qSlicerModulesCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;35;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;0;")
add_test([=[qSlicerModulePanelTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModulesCoreCxxTests" "qSlicerModulePanelTest2")
set_tests_properties([=[qSlicerModulePanelTest2]=] PROPERTIES  LABELS "qSlicerModulesCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;36;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Core/Testing/CMakeLists.txt;0;")
