// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkMRMLCommandLineModuleNode(PyObject *dict); }

static PyMethodDef PyMRMLCLIPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyMRMLCLIPython_Module = {
  PyModuleDef_HEAD_INIT,
  "MRMLCLIPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyMRMLCLIPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initMRMLCLIPython(const char * /*unused*/); }

PyObject *real_initMRMLCLIPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyMRMLCLIPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module MRMLCLIPython");
  }

  const char *depends[5] = {
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
  };

  for (int i = 0; i < 5; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load MRMLCLIPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for MRMLCLIPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkMRMLCommandLineModuleNode(d);

  vtkPythonUtil::AddModule("MRMLCLIPython");

  return m;
}

