// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkITKNumericTraits(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKArchetypeDiffusionTensorImageReaderFile(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKArchetypeImageSeriesReader(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKArchetypeImageSeriesScalarReader(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKArchetypeImageSeriesVectorReaderFile(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKArchetypeImageSeriesVectorReaderSeries(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKImageThresholdCalculator(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKImageWriter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKImageToImageFilter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKImageToImageFilterFF(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKGradientAnisotropicDiffusionImageFilter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKGrowCut(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKDistanceTransform(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKLabelShapeStatistics(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKLevelTracingImageFilter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKLevelTracing3DImageFilter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKIslandMath(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKImageMargin(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkITKMorphologicalContourInterpolator(PyObject *dict); }

static PyMethodDef PyvtkITKPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkITKPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkITKPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkITKPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkITKPython(const char * /*unused*/); }

PyObject *real_initvtkITKPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkITKPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkITKPython");
  }

  vtkPythonUtil::Initialize();

  PyVTKAddFile_vtkITKNumericTraits(d);
  PyVTKAddFile_vtkITKArchetypeDiffusionTensorImageReaderFile(d);
  PyVTKAddFile_vtkITKArchetypeImageSeriesReader(d);
  PyVTKAddFile_vtkITKArchetypeImageSeriesScalarReader(d);
  PyVTKAddFile_vtkITKArchetypeImageSeriesVectorReaderFile(d);
  PyVTKAddFile_vtkITKArchetypeImageSeriesVectorReaderSeries(d);
  PyVTKAddFile_vtkITKImageThresholdCalculator(d);
  PyVTKAddFile_vtkITKImageWriter(d);
  PyVTKAddFile_vtkITKImageToImageFilter(d);
  PyVTKAddFile_vtkITKImageToImageFilterFF(d);
  PyVTKAddFile_vtkITKGradientAnisotropicDiffusionImageFilter(d);
  PyVTKAddFile_vtkITKGrowCut(d);
  PyVTKAddFile_vtkITKDistanceTransform(d);
  PyVTKAddFile_vtkITKLabelShapeStatistics(d);
  PyVTKAddFile_vtkITKLevelTracingImageFilter(d);
  PyVTKAddFile_vtkITKLevelTracing3DImageFilter(d);
  PyVTKAddFile_vtkITKIslandMath(d);
  PyVTKAddFile_vtkITKImageMargin(d);
  PyVTKAddFile_vtkITKMorphologicalContourInterpolator(d);

  vtkPythonUtil::AddModule("vtkITKPython");

  return m;
}

