
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerUnitsModuleWidgets_h
#define __osm_qSlicerUnitsModuleWidgets_h

#include <QObject>
#include "qMRMLSettingsUnitWidget.h"
#include "qMRMLUnitWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSettingsUnitWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSettingsUnitWidget* new_qMRMLSettingsUnitWidget(QWidget*  parent = 0)
    {
    return new qMRMLSettingsUnitWidget(parent);
    }
  void delete_qMRMLSettingsUnitWidget(qMRMLSettingsUnitWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLUnitWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLUnitWidget* new_qMRMLUnitWidget(QWidget*  parent = 0)
    {
    return new qMRMLUnitWidget(parent);
    }
  void delete_qMRMLUnitWidget(qMRMLUnitWidget* obj) { delete obj; }
};

#endif
