# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/DisplayableManager/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vtkMRMLCameraDisplayableManagerTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLCameraDisplayableManagerTest1" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLCameraDisplayableManagerTest1.png")
set_tests_properties([=[vtkMRMLCameraDisplayableManagerTest1]=] PROPERTIES  LABELS "MRMLDisplayableManager" RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLCameraWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLCameraWidgetTest1" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLCameraWidgetTest1.png")
set_tests_properties([=[vtkMRMLCameraWidgetTest1]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLModelDisplayableManagerTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLModelDisplayableManagerTest" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLModelDisplayableManagerTest.png")
set_tests_properties([=[vtkMRMLModelDisplayableManagerTest]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLModelSliceDisplayableManagerTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLModelSliceDisplayableManagerTest" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLModelSliceDisplayableManagerTest.png")
set_tests_properties([=[vtkMRMLModelSliceDisplayableManagerTest]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLThreeDReformatDisplayableManagerTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLThreeDReformatDisplayableManagerTest1" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLThreeDReformatDisplayableManagerTest1.png")
set_tests_properties([=[vtkMRMLThreeDReformatDisplayableManagerTest1]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLThreeDViewDisplayableManagerFactoryTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLThreeDViewDisplayableManagerFactoryTest1" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLThreeDViewDisplayableManagerFactoryTest1.png")
set_tests_properties([=[vtkMRMLThreeDViewDisplayableManagerFactoryTest1]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLDisplayableManagerFactoriesTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLDisplayableManagerFactoriesTest1" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLDisplayableManagerFactoriesTest1.png")
set_tests_properties([=[vtkMRMLDisplayableManagerFactoriesTest1]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceViewDisplayableManagerFactoryTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLDisplayableManagerCxxTests" "vtkMRMLSliceViewDisplayableManagerFactoryTest" "-D" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/../" "-T" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary" "-V" "Baseline/vtkMRMLSliceViewDisplayableManagerFactoryTest.png")
set_tests_properties([=[vtkMRMLSliceViewDisplayableManagerFactoryTest]=] PROPERTIES  LABELS "MRMLDisplayableManager" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;51;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/DisplayableManager/Testing/Cxx/CMakeLists.txt;0;")
