# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Logic/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vtkMRMLAbstractLogicSceneEventsTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLAbstractLogicSceneEventsTest")
set_tests_properties([=[vtkMRMLAbstractLogicSceneEventsTest]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;53;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLColorLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLColorLogicTest1")
set_tests_properties([=[vtkMRMLColorLogicTest1]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;54;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLDisplayableHierarchyLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLDisplayableHierarchyLogicTest1")
set_tests_properties([=[vtkMRMLDisplayableHierarchyLogicTest1]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;55;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLLayoutLogicCompareTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLLayoutLogicCompareTest")
set_tests_properties([=[vtkMRMLLayoutLogicCompareTest]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;56;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLLayoutLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLLayoutLogicTest1")
set_tests_properties([=[vtkMRMLLayoutLogicTest1]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;57;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLLayoutLogicTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLLayoutLogicTest2")
set_tests_properties([=[vtkMRMLLayoutLogicTest2]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;58;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLayerLogicTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLayerLogicTest")
set_tests_properties([=[vtkMRMLSliceLayerLogicTest]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;59;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLogicTest1")
set_tests_properties([=[vtkMRMLSliceLogicTest1]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;60;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLogicTest2_fixed.nrrd]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLogicTest2" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[vtkMRMLSliceLogicTest2_fixed.nrrd]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;49;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;61;simple_file_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLogicTest3_fixed.nrrd]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLogicTest3" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[vtkMRMLSliceLogicTest3_fixed.nrrd]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;49;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;62;simple_file_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLogicTest4_fixed.nrrd]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLogicTest4" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[vtkMRMLSliceLogicTest4_fixed.nrrd]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;49;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;63;simple_file_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLSliceLogicTest5_fixed.nrrd]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLSliceLogicTest5" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[vtkMRMLSliceLogicTest5_fixed.nrrd]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;49;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;64;simple_file_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkMRMLApplicationLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/MRMLLogicCxxTests" "vtkMRMLApplicationLogicTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary")
set_tests_properties([=[vtkMRMLApplicationLogicTest1]=] PROPERTIES  LABELS "MRMLLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;65;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Logic/Testing/Cxx/CMakeLists.txt;0;")
