
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTextsSubjectHierarchyPlugins_h
#define __osm_qSlicerTextsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyTextsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyTextsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyTextsPlugin* new_qSlicerSubjectHierarchyTextsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyTextsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyTextsPlugin(qSlicerSubjectHierarchyTextsPlugin* obj) { delete obj; }
};

#endif
