# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Base/Logic/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vtkDataIOManagerLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/SlicerBaseLogicCxxTests" "vtkDataIOManagerLogicTest1")
set_tests_properties([=[vtkDataIOManagerLogicTest1]=] PROPERTIES  LABELS "SlicerBaseLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;21;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;0;")
add_test([=[vtkSlicerApplicationLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/SlicerBaseLogicCxxTests" "vtkSlicerApplicationLogicTest1")
set_tests_properties([=[vtkSlicerApplicationLogicTest1]=] PROPERTIES  LABELS "SlicerBaseLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;22;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;0;")
add_test([=[vtkSlicerVersionConfigureTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/SlicerBaseLogicCxxTests" "vtkSlicerVersionConfigureTest1")
set_tests_properties([=[vtkSlicerVersionConfigureTest1]=] PROPERTIES  LABELS "SlicerBaseLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;23;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Base/Logic/Testing/CMakeLists.txt;0;")
