// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkMRMLCPURayCastVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLCPURayCastVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLGPURayCastVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLGPURayCastVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLMultiVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLMultiVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLShaderPropertyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLShaderPropertyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLShaderPropertyStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLShaderPropertyStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumePropertyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumePropertyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumePropertyStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumePropertyStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeRenderingDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeRenderingDisplayNode(PyObject *dict); }

static PyMethodDef PyvtkSlicerVolumeRenderingModuleMRMLPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkSlicerVolumeRenderingModuleMRMLPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkSlicerVolumeRenderingModuleMRMLPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkSlicerVolumeRenderingModuleMRMLPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkSlicerVolumeRenderingModuleMRMLPython(const char * /*unused*/); }

PyObject *real_initvtkSlicerVolumeRenderingModuleMRMLPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkSlicerVolumeRenderingModuleMRMLPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkSlicerVolumeRenderingModuleMRMLPython");
  }

  const char *depends[9] = {
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "MRMLLogicPython",
    "MRMLDisplayableManagerPython",
    "MRMLCLIPython",
    "vtkSlicerMarkupsModuleMRMLPython",
  };

  for (int i = 0; i < 9; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load vtkSlicerVolumeRenderingModuleMRMLPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for vtkSlicerVolumeRenderingModuleMRMLPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkMRMLCPURayCastVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLCPURayCastVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLGPURayCastVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLGPURayCastVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLMultiVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLMultiVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLShaderPropertyNode(d);
  PyVTKAddFile_vtkMRMLShaderPropertyNode(d);
  PyVTKAddFile_vtkMRMLShaderPropertyStorageNode(d);
  PyVTKAddFile_vtkMRMLShaderPropertyStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumePropertyNode(d);
  PyVTKAddFile_vtkMRMLVolumePropertyNode(d);
  PyVTKAddFile_vtkMRMLVolumePropertyStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumePropertyStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumeRenderingDisplayNode(d);
  PyVTKAddFile_vtkMRMLVolumeRenderingDisplayNode(d);

  vtkPythonUtil::AddModule("vtkSlicerVolumeRenderingModuleMRMLPython");

  return m;
}

