
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerSegmentationsEditorEffects_h
#define __osm_qSlicerSegmentationsEditorEffects_h

#include <QObject>
#include "qSlicerSegmentEditorEffectFactory.h"
#include "qSlicerSegmentEditorPaintEffect.h"
#include "qSlicerSegmentEditorEraseEffect.h"
#include "qSlicerSegmentEditorScissorsEffect.h"
#include "qSlicerSegmentEditorScriptedEffect.h"
#include "qSlicerSegmentEditorScriptedLabelEffect.h"
#include "qSlicerSegmentEditorScriptedPaintEffect.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorEffectFactory : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorEffectFactory* new_qSlicerSegmentEditorEffectFactory(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorEffectFactory(parent);
    }
  void delete_qSlicerSegmentEditorEffectFactory(qSlicerSegmentEditorEffectFactory* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorPaintEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorPaintEffect* new_qSlicerSegmentEditorPaintEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorPaintEffect(parent);
    }
  void delete_qSlicerSegmentEditorPaintEffect(qSlicerSegmentEditorPaintEffect* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorEraseEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorEraseEffect* new_qSlicerSegmentEditorEraseEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorEraseEffect(parent);
    }
  void delete_qSlicerSegmentEditorEraseEffect(qSlicerSegmentEditorEraseEffect* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorScissorsEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorScissorsEffect* new_qSlicerSegmentEditorScissorsEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorScissorsEffect(parent);
    }
  void delete_qSlicerSegmentEditorScissorsEffect(qSlicerSegmentEditorScissorsEffect* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorScriptedEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorScriptedEffect* new_qSlicerSegmentEditorScriptedEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorScriptedEffect(parent);
    }
  void delete_qSlicerSegmentEditorScriptedEffect(qSlicerSegmentEditorScriptedEffect* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorScriptedLabelEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorScriptedLabelEffect* new_qSlicerSegmentEditorScriptedLabelEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorScriptedLabelEffect(parent);
    }
  void delete_qSlicerSegmentEditorScriptedLabelEffect(qSlicerSegmentEditorScriptedLabelEffect* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSegmentEditorScriptedPaintEffect : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSegmentEditorScriptedPaintEffect* new_qSlicerSegmentEditorScriptedPaintEffect(QObject*  parent = 0)
    {
    return new qSlicerSegmentEditorScriptedPaintEffect(parent);
    }
  void delete_qSlicerSegmentEditorScriptedPaintEffect(qSlicerSegmentEditorScriptedPaintEffect* obj) { delete obj; }
};

#endif
