
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerSegmentationsEditorEffects.h"

void PythonQt_init_osm_qSlicerSegmentationsEditorEffects(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorEffectFactory::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorEffectFactory>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorPaintEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorPaintEffect>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorEraseEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorEraseEffect>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorScissorsEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorScissorsEffect>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorScriptedEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorScriptedEffect>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorScriptedLabelEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorScriptedLabelEffect>);
  

  PythonQt::self()->registerClass(
  &qSlicerSegmentEditorScriptedPaintEffect::staticMetaObject, "qSlicerSegmentationsEditorEffects",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSegmentEditorScriptedPaintEffect>);
  
}
