
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerPlotsModuleWidgets_h
#define __osm_qSlicerPlotsModuleWidgets_h

#include <QObject>
#include "qMRMLPlotSeriesPropertiesWidget.h"
#include "qMRMLPlotChartPropertiesWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLPlotSeriesPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLPlotSeriesPropertiesWidget* new_qMRMLPlotSeriesPropertiesWidget(QWidget*  parent = 0)
    {
    return new qMRMLPlotSeriesPropertiesWidget(parent);
    }
  void delete_qMRMLPlotSeriesPropertiesWidget(qMRMLPlotSeriesPropertiesWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLPlotChartPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLPlotChartPropertiesWidget* new_qMRMLPlotChartPropertiesWidget(QWidget*  parent = 0)
    {
    return new qMRMLPlotChartPropertiesWidget(parent);
    }
  void delete_qMRMLPlotChartPropertiesWidget(qMRMLPlotChartPropertiesWidget* obj) { delete obj; }
};

#endif
