
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerDICOMLibSubjectHierarchyPlugins_h
#define __osm_qSlicerDICOMLibSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyDICOMPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyDICOMPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyDICOMPlugin* new_qSlicerSubjectHierarchyDICOMPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyDICOMPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyDICOMPlugin(qSlicerSubjectHierarchyDICOMPlugin* obj) { delete obj; }
};

#endif
