
#ifndef RESAMPLEDTIVOLUMELIB_EXPORT_H
#define RESAMPLEDTIVOLUMELIB_EXPORT_H

#ifdef RESAMPLEDTIVOLUMELIB_STATIC_DEFINE
#  define RESAMPLEDTIVOLUMELIB_EXPORT
#  define RESAMPLEDTIVOLUMELIB_NO_EXPORT
#else
#  ifndef RESAMPLEDTIVOLUMELIB_EXPORT
#    ifdef ResampleDTIVolumeLib_EXPORTS
        /* We are building this library */
#      define RESAMPLEDTIVOLUMELIB_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define RESAMPLEDTIVOLUMELIB_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef RESAMPLEDTIVOLUMELIB_NO_EXPORT
#    define RESAMPLEDTIVOLUMELIB_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef RESAMPLEDTIVOLUMELIB_DEPRECATED
#  define RESAMPLEDTIVOLUMELIB_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef RESAMPLEDTIVOLUMELIB_DEPRECATED_EXPORT
#  define RESAMPLEDTIVOLUMELIB_DEPRECATED_EXPORT RESAMPLEDTIVOLUMELIB_EXPORT RESAMPLEDTIVOLUMELIB_DEPRECATED
#endif

#ifndef RESAMPLEDTIVOLUMELIB_DEPRECATED_NO_EXPORT
#  define RESAMPLEDTIVOLUMELIB_DEPRECATED_NO_EXPORT RESAMPLEDTIVOLUMELIB_NO_EXPORT RESAMPLEDTIVOLUMELIB_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef RESAMPLEDTIVOLUMELIB_NO_DEPRECATED
#    define RESAMPLEDTIVOLUMELIB_NO_DEPRECATED
#  endif
#endif

#endif /* RESAMPLEDTIVOLUMELIB_EXPORT_H */
