
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerVolumesModuleWidgets.h"

void PythonQt_init_osm_qSlicerVolumesModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerDiffusionTensorVolumeDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDiffusionTensorVolumeDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerDiffusionWeightedVolumeDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDiffusionWeightedVolumeDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerLabelMapVolumeDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerLabelMapVolumeDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerScalarVolumeDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScalarVolumeDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerVolumeDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerVolumeDisplayWidget>);
  

  PythonQt::self()->registerClass(
  &qSlicerDTISliceDisplayWidget::staticMetaObject, "qSlicerVolumesModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qSlicerDTISliceDisplayWidget>);
  
}
