
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerVolumesModuleWidgets_h
#define __osm_qSlicerVolumesModuleWidgets_h

#include <QObject>
#include "qSlicerDiffusionTensorVolumeDisplayWidget.h"
#include "qSlicerDiffusionWeightedVolumeDisplayWidget.h"
#include "qSlicerLabelMapVolumeDisplayWidget.h"
#include "qSlicerScalarVolumeDisplayWidget.h"
#include "qSlicerVolumeDisplayWidget.h"
#include "qSlicerDTISliceDisplayWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDiffusionTensorVolumeDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDiffusionTensorVolumeDisplayWidget* new_qSlicerDiffusionTensorVolumeDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerDiffusionTensorVolumeDisplayWidget(parent);
    }
  void delete_qSlicerDiffusionTensorVolumeDisplayWidget(qSlicerDiffusionTensorVolumeDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDiffusionWeightedVolumeDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDiffusionWeightedVolumeDisplayWidget* new_qSlicerDiffusionWeightedVolumeDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerDiffusionWeightedVolumeDisplayWidget(parent);
    }
  void delete_qSlicerDiffusionWeightedVolumeDisplayWidget(qSlicerDiffusionWeightedVolumeDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerLabelMapVolumeDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerLabelMapVolumeDisplayWidget* new_qSlicerLabelMapVolumeDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerLabelMapVolumeDisplayWidget(parent);
    }
  void delete_qSlicerLabelMapVolumeDisplayWidget(qSlicerLabelMapVolumeDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScalarVolumeDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScalarVolumeDisplayWidget* new_qSlicerScalarVolumeDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerScalarVolumeDisplayWidget(parent);
    }
  void delete_qSlicerScalarVolumeDisplayWidget(qSlicerScalarVolumeDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerVolumeDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerVolumeDisplayWidget* new_qSlicerVolumeDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerVolumeDisplayWidget(parent);
    }
  void delete_qSlicerVolumeDisplayWidget(qSlicerVolumeDisplayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerDTISliceDisplayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerDTISliceDisplayWidget* new_qSlicerDTISliceDisplayWidget(QWidget*  parent = 0)
    {
    return new qSlicerDTISliceDisplayWidget(parent);
    }
  void delete_qSlicerDTISliceDisplayWidget(qSlicerDTISliceDisplayWidget* obj) { delete obj; }
};

#endif
