# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Models/Widgets/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Loadable/Models/Widgets/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[qMRMLModelDisplayNodeWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModelsModuleWidgetsCxxTests" "qMRMLModelDisplayNodeWidgetTest1")
set_tests_properties([=[qMRMLModelDisplayNodeWidgetTest1]=] PROPERTIES  LABELS "qSlicerModelsModuleWidgets" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Models/Widgets/Testing/Cxx/CMakeLists.txt;21;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Models/Widgets/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qMRMLModelDisplayNodeWidgetTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerModelsModuleWidgetsCxxTests" "qMRMLModelDisplayNodeWidgetTest2" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/MRML/Core/Testing/cube.mrml")
set_tests_properties([=[qMRMLModelDisplayNodeWidgetTest2]=] PROPERTIES  LABELS "qSlicerModelsModuleWidgets" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Models/Widgets/Testing/Cxx/CMakeLists.txt;22;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Models/Widgets/Testing/Cxx/CMakeLists.txt;0;")
