// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkSlicerApplicationLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerModuleLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerTask(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkDataIOManagerLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkTransformVisualizerGlyph3D(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkImageRectangularSource(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSystemInformation(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkImageFillROI(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkSlicerScriptedLoadableModuleLogic(PyObject *dict); }

static PyMethodDef PySlicerBaseLogicPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PySlicerBaseLogicPython_Module = {
  PyModuleDef_HEAD_INIT,
  "SlicerBaseLogicPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PySlicerBaseLogicPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initSlicerBaseLogicPython(const char * /*unused*/); }

PyObject *real_initSlicerBaseLogicPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PySlicerBaseLogicPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module SlicerBaseLogicPython");
  }

  const char *depends[7] = {
    "MRMLLogicPython",
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "MRMLCLIPython",
  };

  for (int i = 0; i < 7; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load SlicerBaseLogicPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for SlicerBaseLogicPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkSlicerApplicationLogic(d);
  PyVTKAddFile_vtkSlicerModuleLogic(d);
  PyVTKAddFile_vtkSlicerTask(d);
  PyVTKAddFile_vtkDataIOManagerLogic(d);
  PyVTKAddFile_vtkTransformVisualizerGlyph3D(d);
  PyVTKAddFile_vtkImageRectangularSource(d);
  PyVTKAddFile_vtkSystemInformation(d);
  PyVTKAddFile_vtkImageFillROI(d);
  PyVTKAddFile_vtkSlicerScriptedLoadableModuleLogic(d);

  vtkPythonUtil::AddModule("SlicerBaseLogicPython");

  return m;
}

