// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPython.h"
#include "vtkPythonCompatibility.h"
#include "vtkSystemIncludes.h"
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { PyObject *real_initvtkSlicerSequencesModuleLogicPython(const char * /*unused*/); }

extern  "C" { VTK_ABI_EXPORT PyObject *PyInit_vtkSlicerSequencesModuleLogicPython(); }

PyObject *PyInit_vtkSlicerSequencesModuleLogicPython()
{
  return real_initvtkSlicerSequencesModuleLogicPython(nullptr);
}
