# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[ResampleDTIVolumeRotationNNTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-Rotated.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed1.nrrd" "--compareIntensityTolerance" "0" "ModuleEntryPoint" "-f" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/../Data/Input/rotation.tfm" "--interpolation" "nn" "-c" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed1.nrrd" "-n" "8")
set_tests_properties([=[ResampleDTIVolumeRotationNNTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;26;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[ResampleDTIVolume2RigidTransformsLinearTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-RotationAndAffine.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed2.nrrd" "--compareIntensityTolerance" "1e-10" "ModuleEntryPoint" "-f" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/../Data/Input/rotationAndAffine.tfm" "-T" "FS" "--interpolation" "linear" "-c" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed2.nrrd" "--correction" "abs" "-n" "8")
set_tests_properties([=[ResampleDTIVolume2RigidTransformsLinearTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;46;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[ResampleDTIVolumeBSplineWSInterpolationTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-BS.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed3.nrrd" "--compareIntensityTolerance" "1e-10" "ModuleEntryPoint" "-f" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/../Data/Input/FastNonrigidBSplineregistrationTransform.tfm" "--interpolation" "ws" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed3.nrrd" "--correction" "nearest" "-n" "8")
set_tests_properties([=[ResampleDTIVolumeBSplineWSInterpolationTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;68;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[ResampleDTIVolumeBSplineInterpolationTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-BSInterpolation.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed4.nrrd" "--compareIntensityTolerance" "1e-10" "ModuleEntryPoint" "-f" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/../Data/Input/affine.tfm" "--interpolation" "bs" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed4.nrrd" "--correction" "none" "-o" "3")
set_tests_properties([=[ResampleDTIVolumeBSplineInterpolationTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;88;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[ResampleDTIVolumeHFieldTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-HField.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed5.nrrd" "--compareIntensityTolerance" "0" "ModuleEntryPoint" "-H" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/deformationField.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed5.nrrd" "-n" "8")
set_tests_properties([=[ResampleDTIVolumeHFieldTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;108;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[itkTestMainExtendedScalarTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/Brain_slice.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/Brain_slice.nrrd" "ModuleEntryPoint" "--interpolation" "nn" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed7.nrrd")
set_tests_properties([=[itkTestMainExtendedScalarTest]=] PROPERTIES  LABELS "ResampleDTIVolume" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;131;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
add_test([=[itkTestMainExtendedFailedTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/ResampleDTIVolumeTest" "--compare" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Baseline/dt-helix-ref-HField.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed6.nrrd" "--compareIntensityTolerance" "0" "ModuleEntryPoint" "--interpolation" "nn" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/CLI/ResampleDTIVolume/Data/Input/dt-helix.nrrd" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/dt-helix-transformed6.nrrd")
set_tests_properties([=[itkTestMainExtendedFailedTest]=] PROPERTIES  LABELS "ResampleDTIVolume" WILL_FAIL "true" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;146;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/CLI/ResampleDTIVolume/Testing/CMakeLists.txt;0;")
