
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTablesModuleWidgets_h
#define __osm_qSlicerTablesModuleWidgets_h

#include <QObject>
#include "qSlicerTableColumnPropertiesWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerTableColumnPropertiesWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerTableColumnPropertiesWidget* new_qSlicerTableColumnPropertiesWidget(QWidget*  parent = 0)
    {
    return new qSlicerTableColumnPropertiesWidget(parent);
    }
  void delete_qSlicerTableColumnPropertiesWidget(qSlicerTableColumnPropertiesWidget* obj) { delete obj; }
};

#endif
