# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Extensions/CMake/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[cmake_slicer_extension_description_spec_defaults_test]=] "/usr/bin/cmake" "-DTEST_slicer_extension_description_spec_defaults_test:BOOL=ON" "-P" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/SlicerExtensionDescriptionSpec.cmake")
set_tests_properties([=[cmake_slicer_extension_description_spec_defaults_test]=] PROPERTIES  LABELS "CMake" PASS_REGULAR_EXPRESSION "SUCCESS" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;6;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;18;add_cmakescript_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;0;")
add_test([=[cmake_slicer_extension_metadata_set_defaults_test]=] "/usr/bin/cmake" "-DTEST_slicer_extension_metadata_set_defaults_test:BOOL=ON" "-P" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/SlicerExtensionDescriptionSpec.cmake")
set_tests_properties([=[cmake_slicer_extension_metadata_set_defaults_test]=] PROPERTIES  LABELS "CMake" PASS_REGULAR_EXPRESSION "SUCCESS" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;6;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;22;add_cmakescript_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;0;")
add_test([=[cmake_slicer_extract_extension_description_test]=] "/usr/bin/cmake" "-DTEST_slicer_extract_extension_description_test:BOOL=ON" "-P" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/SlicerFunctionExtractExtensionDescription.cmake")
set_tests_properties([=[cmake_slicer_extract_extension_description_test]=] PROPERTIES  LABELS "CMake" PASS_REGULAR_EXPRESSION "SUCCESS" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;6;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;26;add_cmakescript_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;0;")
add_test([=[cmake_slicer_generate_extension_description_test]=] "/usr/bin/cmake" "-DTEST_slicer_generate_extension_description_test:BOOL=ON" "-P" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/SlicerFunctionGenerateExtensionDescription.cmake")
set_tests_properties([=[cmake_slicer_generate_extension_description_test]=] PROPERTIES  LABELS "CMake" PASS_REGULAR_EXPRESSION "SUCCESS" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;6;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;30;add_cmakescript_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Extensions/CMake/Testing/CMakeLists.txt;0;")
