# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vtkSlicerVolumeRenderingLogicTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSlicerVolumeRenderingModuleLogicCxxTests" "vtkSlicerVolumeRenderingLogicTest" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/share/MINS-5.6/qt-loadable-modules/VolumeRendering")
set_tests_properties([=[vtkSlicerVolumeRenderingLogicTest]=] PROPERTIES  LABELS "vtkSlicerVolumeRenderingModuleLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx/CMakeLists.txt;18;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkSlicerVolumeRenderingLogicAddFromFileTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSlicerVolumeRenderingModuleLogicCxxTests" "vtkSlicerVolumeRenderingLogicAddFromFileTest" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary/")
set_tests_properties([=[vtkSlicerVolumeRenderingLogicAddFromFileTest]=] PROPERTIES  LABELS "vtkSlicerVolumeRenderingModuleLogic" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx/CMakeLists.txt;19;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/VolumeRendering/Logic/Testing/Cxx/CMakeLists.txt;0;")
