
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osb_qSlicerBaseQTCore_h
#define __osb_qSlicerBaseQTCore_h

#include <QObject>
#include "qSlicerAbstractModuleFactoryManager.h"
#include "qSlicerCoreIOManager.h"
#include "qSlicerModuleFactoryManager.h"
#include "qSlicerModuleManager.h"
#include "qSlicerSceneBundleReader.h"
#include "qSlicerScriptedFileReader.h"
#include "qSlicerScriptedFileWriter.h"
#include "qSlicerCorePythonManager.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerAbstractModuleFactoryManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerAbstractModuleFactoryManager* new_qSlicerAbstractModuleFactoryManager(QObject*  parent = 0)
    {
    return new qSlicerAbstractModuleFactoryManager(parent);
    }
  void delete_qSlicerAbstractModuleFactoryManager(qSlicerAbstractModuleFactoryManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerCoreIOManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerCoreIOManager* new_qSlicerCoreIOManager(QObject*  parent = 0)
    {
    return new qSlicerCoreIOManager(parent);
    }
  void delete_qSlicerCoreIOManager(qSlicerCoreIOManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModuleFactoryManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModuleFactoryManager* new_qSlicerModuleFactoryManager(QObject*  parent = 0)
    {
    return new qSlicerModuleFactoryManager(parent);
    }
  void delete_qSlicerModuleFactoryManager(qSlicerModuleFactoryManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerModuleManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerModuleManager* new_qSlicerModuleManager(QObject*  parent = 0)
    {
    return new qSlicerModuleManager(parent);
    }
  void delete_qSlicerModuleManager(qSlicerModuleManager* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSceneBundleReader : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSceneBundleReader* new_qSlicerSceneBundleReader(QObject*  parent = 0)
    {
    return new qSlicerSceneBundleReader(parent);
    }
  void delete_qSlicerSceneBundleReader(qSlicerSceneBundleReader* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScriptedFileReader : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScriptedFileReader* new_qSlicerScriptedFileReader(QObject*  parent = 0)
    {
    return new qSlicerScriptedFileReader(parent);
    }
  void delete_qSlicerScriptedFileReader(qSlicerScriptedFileReader* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerScriptedFileWriter : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerScriptedFileWriter* new_qSlicerScriptedFileWriter(QObject*  parent = 0)
    {
    return new qSlicerScriptedFileWriter(parent);
    }
  void delete_qSlicerScriptedFileWriter(qSlicerScriptedFileWriter* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerCorePythonManager : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerCorePythonManager* new_qSlicerCorePythonManager(QObject*  parent = 0)
    {
    return new qSlicerCorePythonManager(parent);
    }
  void delete_qSlicerCorePythonManager(qSlicerCorePythonManager* obj) { delete obj; }
};

#endif
