
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osb_qSlicerBaseQTCore.h"

void PythonQt_init_osb_qSlicerBaseQTCore(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerAbstractModuleFactoryManager::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerAbstractModuleFactoryManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerCoreIOManager::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerCoreIOManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerModuleFactoryManager::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModuleFactoryManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerModuleManager::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerModuleManager>);
  

  PythonQt::self()->registerClass(
  &qSlicerSceneBundleReader::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerSceneBundleReader>);
  

  PythonQt::self()->registerClass(
  &qSlicerScriptedFileReader::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScriptedFileReader>);
  

  PythonQt::self()->registerClass(
  &qSlicerScriptedFileWriter::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerScriptedFileWriter>);
  

  PythonQt::self()->registerClass(
  &qSlicerCorePythonManager::staticMetaObject, "qSlicerBaseQTCore",
  PythonQtCreateObject<PythonQtWrapper_qSlicerCorePythonManager>);
  
}
