// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkArchive(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkArchive(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkCodedEntry(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkEventBroker(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkDataFileFormatHelper(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLI18N(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLI18N(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLMeasurement(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLStaticMeasurement(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLogic(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLAbstractLayoutNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLAbstractViewNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLCameraNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLClipModelsNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLColorNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLColors(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLColorTableNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLColorTableStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLCoreTestingUtilities(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLCrosshairNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionTensorDisplayPropertiesNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionWeightedVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionWeightedVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDisplayableNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLFolderDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLHierarchyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLHierarchyStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDisplayableHierarchyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLInteractionNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLabelMapVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLabelMapVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLinearTransformNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLinearTransformSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLinearTransformSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLMarkupsStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLMessageCollection(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLModelDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLModelHierarchyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLModelNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLModelStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLParser(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLPlotChartNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLPlotSeriesNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLPlotViewNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLProceduralColorNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLProceduralColorStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLROIListNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLROINode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLScalarVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLScalarVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLScene(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSceneViewNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSceneViewStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLScriptedModuleNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLScriptedModuleNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSequenceNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSequenceNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSelectionNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSliceCompositeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSliceDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSliceNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSnapshotClipNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLStorableNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSubjectHierarchyConstants(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSubjectHierarchyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSubjectHierarchyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSubjectHierarchyLegacyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSubjectHierarchyLegacyNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTableNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTableStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTableSQLiteStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTableViewNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTextNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTextStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTransformableNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTranslator(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLUnitNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVectorVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLViewNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeArchetypeStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLGlyphableVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLGlyphableVolumeSliceDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeHeaderlessStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVolumeSequenceStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkObservation(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkObserverManager(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLLayoutNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkCacheManager(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkDataIOManager(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkDataTransfer(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLBSplineTransformNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLGridTransformNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkPermissionPrompter(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkURIHandler(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkTagTableCollection(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkTagTable(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLdGEMRICProceduralColorNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLPETProceduralColorNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionImageVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionTensorVolumeDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionTensorVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLDiffusionTensorVolumeSliceDisplayNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLNRRDStorageNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLTensorVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLVectorVolumeNode(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLStreamingVolumeNode(PyObject *dict); }

static PyMethodDef PyMRMLCorePython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyMRMLCorePython_Module = {
  PyModuleDef_HEAD_INIT,
  "MRMLCorePython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyMRMLCorePython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initMRMLCorePython(const char * /*unused*/); }

PyObject *real_initMRMLCorePython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyMRMLCorePython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module MRMLCorePython");
  }

  const char *depends[4] = {
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
  };

  for (int i = 0; i < 4; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load MRMLCorePython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for MRMLCorePython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkArchive(d);
  PyVTKAddFile_vtkArchive(d);
  PyVTKAddFile_vtkCodedEntry(d);
  PyVTKAddFile_vtkEventBroker(d);
  PyVTKAddFile_vtkDataFileFormatHelper(d);
  PyVTKAddFile_vtkMRMLI18N(d);
  PyVTKAddFile_vtkMRMLI18N(d);
  PyVTKAddFile_vtkMRMLMeasurement(d);
  PyVTKAddFile_vtkMRMLStaticMeasurement(d);
  PyVTKAddFile_vtkMRMLLogic(d);
  PyVTKAddFile_vtkMRMLAbstractLayoutNode(d);
  PyVTKAddFile_vtkMRMLAbstractViewNode(d);
  PyVTKAddFile_vtkMRMLCameraNode(d);
  PyVTKAddFile_vtkMRMLClipModelsNode(d);
  PyVTKAddFile_vtkMRMLColorNode(d);
  PyVTKAddFile_vtkMRMLColors(d);
  PyVTKAddFile_vtkMRMLColorTableNode(d);
  PyVTKAddFile_vtkMRMLColorTableStorageNode(d);
  PyVTKAddFile_vtkMRMLCoreTestingUtilities(d);
  PyVTKAddFile_vtkMRMLCrosshairNode(d);
  PyVTKAddFile_vtkMRMLDiffusionTensorDisplayPropertiesNode(d);
  PyVTKAddFile_vtkMRMLDiffusionWeightedVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLDiffusionWeightedVolumeNode(d);
  PyVTKAddFile_vtkMRMLDisplayNode(d);
  PyVTKAddFile_vtkMRMLDisplayableNode(d);
  PyVTKAddFile_vtkMRMLFolderDisplayNode(d);
  PyVTKAddFile_vtkMRMLHierarchyNode(d);
  PyVTKAddFile_vtkMRMLHierarchyStorageNode(d);
  PyVTKAddFile_vtkMRMLDisplayableHierarchyNode(d);
  PyVTKAddFile_vtkMRMLInteractionNode(d);
  PyVTKAddFile_vtkMRMLLabelMapVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLLabelMapVolumeNode(d);
  PyVTKAddFile_vtkMRMLLinearTransformNode(d);
  PyVTKAddFile_vtkMRMLLinearTransformSequenceStorageNode(d);
  PyVTKAddFile_vtkMRMLLinearTransformSequenceStorageNode(d);
  PyVTKAddFile_vtkMRMLMarkupsStorageNode(d);
  PyVTKAddFile_vtkMRMLMessageCollection(d);
  PyVTKAddFile_vtkMRMLModelDisplayNode(d);
  PyVTKAddFile_vtkMRMLModelHierarchyNode(d);
  PyVTKAddFile_vtkMRMLModelNode(d);
  PyVTKAddFile_vtkMRMLModelStorageNode(d);
  PyVTKAddFile_vtkMRMLNode(d);
  PyVTKAddFile_vtkMRMLParser(d);
  PyVTKAddFile_vtkMRMLPlotChartNode(d);
  PyVTKAddFile_vtkMRMLPlotSeriesNode(d);
  PyVTKAddFile_vtkMRMLPlotViewNode(d);
  PyVTKAddFile_vtkMRMLProceduralColorNode(d);
  PyVTKAddFile_vtkMRMLProceduralColorStorageNode(d);
  PyVTKAddFile_vtkMRMLROIListNode(d);
  PyVTKAddFile_vtkMRMLROINode(d);
  PyVTKAddFile_vtkMRMLScalarVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLScalarVolumeNode(d);
  PyVTKAddFile_vtkMRMLScene(d);
  PyVTKAddFile_vtkMRMLSceneViewNode(d);
  PyVTKAddFile_vtkMRMLSceneViewStorageNode(d);
  PyVTKAddFile_vtkMRMLScriptedModuleNode(d);
  PyVTKAddFile_vtkMRMLScriptedModuleNode(d);
  PyVTKAddFile_vtkMRMLSegmentationNode(d);
  PyVTKAddFile_vtkMRMLSegmentationNode(d);
  PyVTKAddFile_vtkMRMLSegmentationDisplayNode(d);
  PyVTKAddFile_vtkMRMLSegmentationDisplayNode(d);
  PyVTKAddFile_vtkMRMLSegmentationStorageNode(d);
  PyVTKAddFile_vtkMRMLSegmentationStorageNode(d);
  PyVTKAddFile_vtkMRMLSequenceNode(d);
  PyVTKAddFile_vtkMRMLSequenceNode(d);
  PyVTKAddFile_vtkMRMLSequenceStorageNode(d);
  PyVTKAddFile_vtkMRMLSequenceStorageNode(d);
  PyVTKAddFile_vtkMRMLSelectionNode(d);
  PyVTKAddFile_vtkMRMLSliceCompositeNode(d);
  PyVTKAddFile_vtkMRMLSliceDisplayNode(d);
  PyVTKAddFile_vtkMRMLSliceNode(d);
  PyVTKAddFile_vtkMRMLSnapshotClipNode(d);
  PyVTKAddFile_vtkMRMLStorableNode(d);
  PyVTKAddFile_vtkMRMLStorageNode(d);
  PyVTKAddFile_vtkMRMLSubjectHierarchyConstants(d);
  PyVTKAddFile_vtkMRMLSubjectHierarchyNode(d);
  PyVTKAddFile_vtkMRMLSubjectHierarchyNode(d);
  PyVTKAddFile_vtkMRMLSubjectHierarchyLegacyNode(d);
  PyVTKAddFile_vtkMRMLSubjectHierarchyLegacyNode(d);
  PyVTKAddFile_vtkMRMLTableNode(d);
  PyVTKAddFile_vtkMRMLTableStorageNode(d);
  PyVTKAddFile_vtkMRMLTableSQLiteStorageNode(d);
  PyVTKAddFile_vtkMRMLTableViewNode(d);
  PyVTKAddFile_vtkMRMLTextNode(d);
  PyVTKAddFile_vtkMRMLTextStorageNode(d);
  PyVTKAddFile_vtkMRMLTransformNode(d);
  PyVTKAddFile_vtkMRMLTransformStorageNode(d);
  PyVTKAddFile_vtkMRMLTransformDisplayNode(d);
  PyVTKAddFile_vtkMRMLTransformableNode(d);
  PyVTKAddFile_vtkMRMLTranslator(d);
  PyVTKAddFile_vtkMRMLUnitNode(d);
  PyVTKAddFile_vtkMRMLVectorVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLViewNode(d);
  PyVTKAddFile_vtkMRMLVolumeArchetypeStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLGlyphableVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLGlyphableVolumeSliceDisplayNode(d);
  PyVTKAddFile_vtkMRMLVolumeHeaderlessStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumeNode(d);
  PyVTKAddFile_vtkMRMLVolumeSequenceStorageNode(d);
  PyVTKAddFile_vtkMRMLVolumeSequenceStorageNode(d);
  PyVTKAddFile_vtkObservation(d);
  PyVTKAddFile_vtkObserverManager(d);
  PyVTKAddFile_vtkMRMLLayoutNode(d);
  PyVTKAddFile_vtkCacheManager(d);
  PyVTKAddFile_vtkDataIOManager(d);
  PyVTKAddFile_vtkDataTransfer(d);
  PyVTKAddFile_vtkMRMLBSplineTransformNode(d);
  PyVTKAddFile_vtkMRMLGridTransformNode(d);
  PyVTKAddFile_vtkPermissionPrompter(d);
  PyVTKAddFile_vtkURIHandler(d);
  PyVTKAddFile_vtkTagTableCollection(d);
  PyVTKAddFile_vtkTagTable(d);
  PyVTKAddFile_vtkMRMLdGEMRICProceduralColorNode(d);
  PyVTKAddFile_vtkMRMLPETProceduralColorNode(d);
  PyVTKAddFile_vtkMRMLDiffusionImageVolumeNode(d);
  PyVTKAddFile_vtkMRMLDiffusionTensorVolumeDisplayNode(d);
  PyVTKAddFile_vtkMRMLDiffusionTensorVolumeNode(d);
  PyVTKAddFile_vtkMRMLDiffusionTensorVolumeSliceDisplayNode(d);
  PyVTKAddFile_vtkMRMLNRRDStorageNode(d);
  PyVTKAddFile_vtkMRMLTensorVolumeNode(d);
  PyVTKAddFile_vtkMRMLVectorVolumeNode(d);
  PyVTKAddFile_vtkMRMLStreamingVolumeNode(d);

  vtkPythonUtil::AddModule("MRMLCorePython");

  return m;
}

