
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTransformsSubjectHierarchyPlugins_h
#define __osm_qSlicerTransformsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyTransformsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyTransformsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyTransformsPlugin* new_qSlicerSubjectHierarchyTransformsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyTransformsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyTransformsPlugin(qSlicerSubjectHierarchyTransformsPlugin* obj) { delete obj; }
};

#endif
