
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTablesSubjectHierarchyPlugins_h
#define __osm_qSlicerTablesSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyTablesPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyTablesPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyTablesPlugin* new_qSlicerSubjectHierarchyTablesPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyTablesPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyTablesPlugin(qSlicerSubjectHierarchyTablesPlugin* obj) { delete obj; }
};

#endif
