# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Loadable/Volumes/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[qSlicerVolumesIOOptionsWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumesModuleCxxTests" "qSlicerVolumesIOOptionsWidgetTest1")
set_tests_properties([=[qSlicerVolumesIOOptionsWidgetTest1]=] PROPERTIES  LABELS "qSlicerVolumesModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;47;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[qSlicerVolumesModuleWidgetTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumesModuleCxxTests" "qSlicerVolumesModuleWidgetTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[qSlicerVolumesModuleWidgetTest1]=] PROPERTIES  LABELS "qSlicerVolumesModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;48;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkSlicerVolumesLogicTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumesModuleCxxTests" "vtkSlicerVolumesLogicTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[vtkSlicerVolumesLogicTest1]=] PROPERTIES  LABELS "qSlicerVolumesModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;49;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkSlicerVolumesLogicTest1_TestNAN]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/qSlicerVolumesModuleCxxTests" "vtkSlicerVolumesLogicTest1" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Applications/SlicerApp/Data/Input/testNANInVolume.nrrd")
set_tests_properties([=[vtkSlicerVolumesLogicTest1_TestNAN]=] PROPERTIES  LABELS "qSlicerVolumesModule" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;50;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;0;")
add_test([=[vtkSlicerVolumesLogicTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSlicerVolumesLogicTest2" "vtkSlicerVolumesLogicTest2" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Testing/Temporary")
set_tests_properties([=[vtkSlicerVolumesLogicTest2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;59;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Loadable/Volumes/Testing/Cxx/CMakeLists.txt;0;")
