
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerModelsModuleWidgets_h
#define __osm_qSlicerModelsModuleWidgets_h

#include <QObject>
#include "qMRMLModelDisplayNodeWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLModelDisplayNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLModelDisplayNodeWidget* new_qMRMLModelDisplayNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLModelDisplayNodeWidget(parent);
    }
  void delete_qMRMLModelDisplayNodeWidget(qMRMLModelDisplayNodeWidget* obj) { delete obj; }
};

#endif
