
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTextsModuleWidgets_h
#define __osm_qSlicerTextsModuleWidgets_h

#include <QObject>
#include "qMRMLTextWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLTextWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLTextWidget* new_qMRMLTextWidget(QWidget*  parent = 0)
    {
    return new qMRMLTextWidget(parent);
    }
  void delete_qMRMLTextWidget(qMRMLTextWidget* obj) { delete obj; }
};

#endif
