
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osb_qSlicerBaseQTApp_h
#define __osb_qSlicerBaseQTApp_h

#include <QObject>
#include "qSlicerAboutDialog.h"
#include "qSlicerApplicationHelper.h"
#include "qSlicerErrorReportDialog.h"
#include "qSlicerMainWindow.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerAboutDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerAboutDialog* new_qSlicerAboutDialog(QWidget*  parent = 0)
    {
    return new qSlicerAboutDialog(parent);
    }
  void delete_qSlicerAboutDialog(qSlicerAboutDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerApplicationHelper : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerApplicationHelper* new_qSlicerApplicationHelper(QObject*  parent = 0)
    {
    return new qSlicerApplicationHelper(parent);
    }
  void delete_qSlicerApplicationHelper(qSlicerApplicationHelper* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerErrorReportDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerErrorReportDialog* new_qSlicerErrorReportDialog(QWidget*  parent = 0)
    {
    return new qSlicerErrorReportDialog(parent);
    }
  void delete_qSlicerErrorReportDialog(qSlicerErrorReportDialog* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerMainWindow : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerMainWindow* new_qSlicerMainWindow(QWidget*  parent = 0)
    {
    return new qSlicerMainWindow(parent);
    }
  void delete_qSlicerMainWindow(qSlicerMainWindow* obj) { delete obj; }
};

#endif
