
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osb_qSlicerBaseQTApp.h"

void PythonQt_init_osb_qSlicerBaseQTApp(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qSlicerAboutDialog::staticMetaObject, "qSlicerBaseQTApp",
  PythonQtCreateObject<PythonQtWrapper_qSlicerAboutDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerApplicationHelper::staticMetaObject, "qSlicerBaseQTApp",
  PythonQtCreateObject<PythonQtWrapper_qSlicerApplicationHelper>);
  

  PythonQt::self()->registerClass(
  &qSlicerErrorReportDialog::staticMetaObject, "qSlicerBaseQTApp",
  PythonQtCreateObject<PythonQtWrapper_qSlicerErrorReportDialog>);
  

  PythonQt::self()->registerClass(
  &qSlicerMainWindow::staticMetaObject, "qSlicerBaseQTApp",
  PythonQtCreateObject<PythonQtWrapper_qSlicerMainWindow>);
  
}
