
#ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT_H
#define RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT_H

#ifdef RESAMPLESCALARVECTORDWIVOLUMELIB_STATIC_DEFINE
#  define RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT
#  define RESAMPLESCALARVECTORDWIVOLUMELIB_NO_EXPORT
#else
#  ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT
#    ifdef ResampleScalarVectorDWIVolumeLib_EXPORTS
        /* We are building this library */
#      define RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_NO_EXPORT
#    define RESAMPLESCALARVECTORDWIVOLUMELIB_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED
#  define RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED_EXPORT
#  define RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED_EXPORT RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED
#endif

#ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED_NO_EXPORT
#  define RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED_NO_EXPORT RESAMPLESCALARVECTORDWIVOLUMELIB_NO_EXPORT RESAMPLESCALARVECTORDWIVOLUMELIB_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef RESAMPLESCALARVECTORDWIVOLUMELIB_NO_DEPRECATED
#    define RESAMPLESCALARVECTORDWIVOLUMELIB_NO_DEPRECATED
#  endif
#endif

#endif /* RESAMPLESCALARVECTORDWIVOLUMELIB_EXPORT_H */
