# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/vtkITK/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[VTKITKVectorReader]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/VTKITKVectorReader" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/MRML/Core/Testing/TestData/fixed.nrrd")
set_tests_properties([=[VTKITKVectorReader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;14;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;0;")
add_test([=[py_vtkITKArchetypeDiffusionTensorReaderFile]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/vtkITK/Testing', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing'], 'vtkITKArchetypeDiffusionTensorReaderFile')")
set_tests_properties([=[py_vtkITKArchetypeDiffusionTensorReaderFile]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;20;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;0;")
add_test([=[py_vtkITKArchetypeScalarReaderFile]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/vtkITK/Testing', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing'], 'vtkITKArchetypeScalarReaderFile')")
set_tests_properties([=[py_vtkITKArchetypeScalarReaderFile]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;21;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkITK/Testing/CMakeLists.txt;0;")
