# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/CropVolumeSequence
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[py_nomainwindow_qSlicerCropVolumeSequenceModuleGenericTest]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--no-main-window" "--disable-cli-modules" "--additional-module-path" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/CropVolumeSequence', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence'], 'qSlicerCropVolumeSequenceModuleGenericTest')")
set_tests_properties([=[py_nomainwindow_qSlicerCropVolumeSequenceModuleGenericTest]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroBuildScriptedModule.cmake;114;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence/CMakeLists.txt;14;slicerMacroBuildScriptedModule;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence/CMakeLists.txt;0;")
add_test([=[py_CropVolumeSequence]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--no-splash" "--testing" "--additional-module-paths" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-loadable-modules" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/lib/MINS-5.6/qt-scripted-modules" "--python-code" "import slicer.testing; slicer.testing.runUnitTest(['/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Modules/Scripted/CropVolumeSequence', '/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence'], 'CropVolumeSequence')")
set_tests_properties([=[py_CropVolumeSequence]=] PROPERTIES  RUN_SERIAL "TRUE" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroPythonTesting.cmake;86;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence/CMakeLists.txt;35;slicer_add_python_unittest;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Modules/Scripted/CropVolumeSequence/CMakeLists.txt;0;")
subdirs("Testing")
