
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerTerminologiesModuleWidgets_h
#define __osm_qSlicerTerminologiesModuleWidgets_h

#include <QObject>
#include "qSlicerTerminologyItemDelegate.h"
#include "qSlicerTerminologyNavigatorWidget.h"
#include "qSlicerTerminologySelectorButton.h"
#include "qSlicerTerminologySelectorDialog.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerTerminologyItemDelegate : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerTerminologyItemDelegate* new_qSlicerTerminologyItemDelegate(QObject*  parent = 0)
    {
    return new qSlicerTerminologyItemDelegate(parent);
    }
  void delete_qSlicerTerminologyItemDelegate(qSlicerTerminologyItemDelegate* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerTerminologyNavigatorWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerTerminologyNavigatorWidget* new_qSlicerTerminologyNavigatorWidget(QWidget*  parent = 0)
    {
    return new qSlicerTerminologyNavigatorWidget(parent);
    }
  void delete_qSlicerTerminologyNavigatorWidget(qSlicerTerminologyNavigatorWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerTerminologySelectorButton : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerTerminologySelectorButton* new_qSlicerTerminologySelectorButton(QWidget*  parent = 0)
    {
    return new qSlicerTerminologySelectorButton(parent);
    }
  void delete_qSlicerTerminologySelectorButton(qSlicerTerminologySelectorButton* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerTerminologySelectorDialog : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerTerminologySelectorDialog* new_qSlicerTerminologySelectorDialog(QObject*  parent = 0)
    {
    return new qSlicerTerminologySelectorDialog(parent);
    }
  void delete_qSlicerTerminologySelectorDialog(qSlicerTerminologySelectorDialog* obj) { delete obj; }
};

#endif
