
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerColorsModuleWidgets_h
#define __osm_qSlicerColorsModuleWidgets_h

#include <QObject>
#include "qMRMLColorLegendDisplayNodeWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLColorLegendDisplayNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLColorLegendDisplayNodeWidget* new_qMRMLColorLegendDisplayNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLColorLegendDisplayNodeWidget(parent);
    }
  void delete_qMRMLColorLegendDisplayNodeWidget(qMRMLColorLegendDisplayNodeWidget* obj) { delete obj; }
};

#endif
