// Generated by vtkWrapPythonInit in VTK/Wrapping
#include "vtkPythonUtil.h"
#include "vtkSystemIncludes.h"
#include <cstring>
// Handle compiler warning messages, etc.
#if defined( _MSC_VER ) && !defined(VTK_DISPLAY_WIN32_WARNINGS)
#pragma warning ( disable : 4706 )
#endif // Windows Warnings

extern "C" { void PyVTKAddFile_vtkSlicerSegmentationsModuleMRMLDisplayableManagerObjectFactory(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationsDisplayableManager3D(PyObject *dict); }
extern "C" { void PyVTKAddFile_vtkMRMLSegmentationsDisplayableManager2D(PyObject *dict); }

static PyMethodDef PyvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython_Methods[] = {
{nullptr, nullptr, 0, nullptr}};

static PyModuleDef PyvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython_Module = {
  PyModuleDef_HEAD_INIT,
  "vtkSlicerSegmentationsModuleMRMLDisplayableManagerPython", // m_name
  nullptr, // m_doc
  0, // m_size
  PyvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython_Methods, //m_methods
  nullptr, // m_reload
  nullptr, // m_traverse
  nullptr, // m_clear
  nullptr  // m_free
};
extern  "C" {VTK_ABI_EXPORT PyObject *real_initvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython(const char * /*unused*/); }

PyObject *real_initvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython(const char * /*unused*/)
{
  PyObject *m = PyModule_Create(&PyvtkSlicerSegmentationsModuleMRMLDisplayableManagerPython_Module);
  PyObject *d = PyModule_GetDict(m);
  if (!d)
  {
    Py_FatalError("can't get dictionary for module vtkSlicerSegmentationsModuleMRMLDisplayableManagerPython");
  }

  const char *depends[12] = {
    "MRMLCorePython",
    "vtkAddonPython",
    "vtkITKPython",
    "vtkSegmentationCorePython",
    "vtkTeemPython",
    "MRMLLogicPython",
    "MRMLDisplayableManagerPython",
    "MRMLCLIPython",
    "vtkSlicerSegmentationsModuleMRMLPython",
    "vtkSlicerSubjectHierarchyModuleLogicPython",
    "qSlicerBaseQTCLIPython",
    "SlicerBaseLogicPython",
  };

  for (int i = 0; i < 12; i++)
  {
    if (!vtkPythonUtil::ImportModule(depends[i], d))
    {
      Py_DECREF(m);
      return PyErr_Format(PyExc_ImportError,
        "Failed to load vtkSlicerSegmentationsModuleMRMLDisplayableManagerPython: No module named %s",
        depends[i]);
    }
  }

  if (!vtkPythonUtil::IsInitialized())
  {
    Py_DECREF(m);
    return PyErr_Format(PyExc_ImportError,
      "Initialization failed for vtkSlicerSegmentationsModuleMRMLDisplayableManagerPython, not compatible with %s",
      depends[0]);
  }

  PyVTKAddFile_vtkSlicerSegmentationsModuleMRMLDisplayableManagerObjectFactory(d);
  PyVTKAddFile_vtkMRMLSegmentationsDisplayableManager3D(d);
  PyVTKAddFile_vtkMRMLSegmentationsDisplayableManager2D(d);

  vtkPythonUtil::AddModule("vtkSlicerSegmentationsModuleMRMLDisplayableManagerPython");

  return m;
}

