
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerModelsSubjectHierarchyPlugins_h
#define __osm_qSlicerModelsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchyModelsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchyModelsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchyModelsPlugin* new_qSlicerSubjectHierarchyModelsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchyModelsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchyModelsPlugin(qSlicerSubjectHierarchyModelsPlugin* obj) { delete obj; }
};

#endif
