
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerSegmentationsModuleWidgets_h
#define __osm_qSlicerSegmentationsModuleWidgets_h

#include <QObject>
#include "qMRMLDoubleSpinBoxDelegate.h"
#include "qMRMLSegmentsModel.h"
#include "qMRMLSegmentsTableView.h"
#include "qMRMLSegmentationConversionParametersWidget.h"
#include "qMRMLSegmentationDisplayNodeWidget.h"
#include "qMRMLSegmentationFileExportWidget.h"
#include "qMRMLSegmentationGeometryWidget.h"
#include "qMRMLSegmentationRepresentationsListView.h"
#include "qMRMLSegmentationShow3DButton.h"
#include "qMRMLSegmentEditorWidget.h"
#include "qMRMLSortFilterSegmentsProxyModel.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLDoubleSpinBoxDelegate : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLDoubleSpinBoxDelegate* new_qMRMLDoubleSpinBoxDelegate(QObject*  parent = 0)
    {
    return new qMRMLDoubleSpinBoxDelegate(parent);
    }
  void delete_qMRMLDoubleSpinBoxDelegate(qMRMLDoubleSpinBoxDelegate* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentsModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentsModel* new_qMRMLSegmentsModel(QObject*  parent = 0)
    {
    return new qMRMLSegmentsModel(parent);
    }
  void delete_qMRMLSegmentsModel(qMRMLSegmentsModel* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentsTableView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentsTableView* new_qMRMLSegmentsTableView(QWidget*  parent = 0)
    {
    return new qMRMLSegmentsTableView(parent);
    }
  void delete_qMRMLSegmentsTableView(qMRMLSegmentsTableView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationConversionParametersWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationConversionParametersWidget* new_qMRMLSegmentationConversionParametersWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationConversionParametersWidget(parent);
    }
  void delete_qMRMLSegmentationConversionParametersWidget(qMRMLSegmentationConversionParametersWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationDisplayNodeWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationDisplayNodeWidget* new_qMRMLSegmentationDisplayNodeWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationDisplayNodeWidget(parent);
    }
  void delete_qMRMLSegmentationDisplayNodeWidget(qMRMLSegmentationDisplayNodeWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationFileExportWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationFileExportWidget* new_qMRMLSegmentationFileExportWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationFileExportWidget(parent);
    }
  void delete_qMRMLSegmentationFileExportWidget(qMRMLSegmentationFileExportWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationGeometryWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationGeometryWidget* new_qMRMLSegmentationGeometryWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationGeometryWidget(parent);
    }
  void delete_qMRMLSegmentationGeometryWidget(qMRMLSegmentationGeometryWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationRepresentationsListView : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationRepresentationsListView* new_qMRMLSegmentationRepresentationsListView(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationRepresentationsListView(parent);
    }
  void delete_qMRMLSegmentationRepresentationsListView(qMRMLSegmentationRepresentationsListView* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentationShow3DButton : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentationShow3DButton* new_qMRMLSegmentationShow3DButton(QWidget*  parent = 0)
    {
    return new qMRMLSegmentationShow3DButton(parent);
    }
  void delete_qMRMLSegmentationShow3DButton(qMRMLSegmentationShow3DButton* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSegmentEditorWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSegmentEditorWidget* new_qMRMLSegmentEditorWidget(QWidget*  parent = 0)
    {
    return new qMRMLSegmentEditorWidget(parent);
    }
  void delete_qMRMLSegmentEditorWidget(qMRMLSegmentEditorWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSortFilterSegmentsProxyModel : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSortFilterSegmentsProxyModel* new_qMRMLSortFilterSegmentsProxyModel(QObject*  parent = 0)
    {
    return new qMRMLSortFilterSegmentsProxyModel(parent);
    }
  void delete_qMRMLSortFilterSegmentsProxyModel(qMRMLSortFilterSegmentsProxyModel* obj) { delete obj; }
};

#endif
