
//
// File auto-generated by ctkWrapPythonQt.py
//

#include <PythonQt.h>
// XXX Avoid  warning: "HAVE_XXXX" redefined
#undef HAVE_STAT
#undef HAVE_FTIME
#undef HAVE_GETPID
#undef HAVE_IO_H
#undef HAVE_STRERROR
#undef HAVE_SYS_UTIME_H
#undef HAVE_TEMPNAM
#undef HAVE_TMPNAM
#undef HAVE_LONG_LONG
#undef HAVE_INT64_T
#include "osm_qSlicerSegmentationsModuleWidgets.h"

void PythonQt_init_osm_qSlicerSegmentationsModuleWidgets(PyObject* module)
{
  Q_UNUSED(module);
  
  PythonQt::self()->registerClass(
  &qMRMLDoubleSpinBoxDelegate::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLDoubleSpinBoxDelegate>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentsModel::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentsModel>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentsTableView::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentsTableView>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationConversionParametersWidget::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationConversionParametersWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationDisplayNodeWidget::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationDisplayNodeWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationFileExportWidget::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationFileExportWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationGeometryWidget::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationGeometryWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationRepresentationsListView::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationRepresentationsListView>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentationShow3DButton::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentationShow3DButton>);
  

  PythonQt::self()->registerClass(
  &qMRMLSegmentEditorWidget::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSegmentEditorWidget>);
  

  PythonQt::self()->registerClass(
  &qMRMLSortFilterSegmentsProxyModel::staticMetaObject, "qSlicerSegmentationsModuleWidgets",
  PythonQtCreateObject<PythonQtWrapper_qMRMLSortFilterSegmentsProxyModel>);
  
}
