
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerSequencesModuleWidgets_h
#define __osm_qSlicerSequencesModuleWidgets_h

#include <QObject>
#include "qMRMLSequenceBrowserPlayWidget.h"
#include "qMRMLSequenceBrowserSeekWidget.h"
#include "qMRMLSequenceBrowserToolBar.h"
#include "qMRMLSequenceEditWidget.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSequenceBrowserPlayWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSequenceBrowserPlayWidget* new_qMRMLSequenceBrowserPlayWidget(QWidget*  parent = 0)
    {
    return new qMRMLSequenceBrowserPlayWidget(parent);
    }
  void delete_qMRMLSequenceBrowserPlayWidget(qMRMLSequenceBrowserPlayWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSequenceBrowserSeekWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSequenceBrowserSeekWidget* new_qMRMLSequenceBrowserSeekWidget(QWidget*  parent = 0)
    {
    return new qMRMLSequenceBrowserSeekWidget(parent);
    }
  void delete_qMRMLSequenceBrowserSeekWidget(qMRMLSequenceBrowserSeekWidget* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSequenceBrowserToolBar : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSequenceBrowserToolBar* new_qMRMLSequenceBrowserToolBar(QWidget*  parent = 0)
    {
    return new qMRMLSequenceBrowserToolBar(parent);
    }
  void delete_qMRMLSequenceBrowserToolBar(qMRMLSequenceBrowserToolBar* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qMRMLSequenceEditWidget : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qMRMLSequenceEditWidget* new_qMRMLSequenceEditWidget(QWidget*  parent = 0)
    {
    return new qMRMLSequenceEditWidget(parent);
    }
  void delete_qMRMLSequenceEditWidget(qMRMLSequenceEditWidget* obj) { delete obj; }
};

#endif
