
//
// File auto-generated by ctkWrapPythonQt.py
//

#ifndef __osm_qSlicerSegmentationsSubjectHierarchyPlugins_h
#define __osm_qSlicerSegmentationsSubjectHierarchyPlugins_h

#include <QObject>
#include "qSlicerSubjectHierarchySegmentationsPlugin.h"
#include "qSlicerSubjectHierarchySegmentsPlugin.h"

//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchySegmentationsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchySegmentationsPlugin* new_qSlicerSubjectHierarchySegmentationsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchySegmentationsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchySegmentationsPlugin(qSlicerSubjectHierarchySegmentationsPlugin* obj) { delete obj; }
};


//-----------------------------------------------------------------------------
class PythonQtWrapper_qSlicerSubjectHierarchySegmentsPlugin : public QObject
{
Q_OBJECT
public:
public Q_SLOTS:
  qSlicerSubjectHierarchySegmentsPlugin* new_qSlicerSubjectHierarchySegmentsPlugin(QObject*  parent = 0)
    {
    return new qSlicerSubjectHierarchySegmentsPlugin(parent);
    }
  void delete_qSlicerSubjectHierarchySegmentsPlugin(qSlicerSubjectHierarchySegmentsPlugin* obj) { delete obj; }
};

#endif
