# CMake generated Testfile for 
# Source directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing
# Build directory: /home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/Libs/vtkSegmentationCore/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vtkSegmentationTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSegmentationCoreCxxTests" "vtkSegmentationTest1")
set_tests_properties([=[vtkSegmentationTest1]=] PROPERTIES  LABELS "vtkSegmentationCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;15;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;0;")
add_test([=[vtkSegmentationTest2]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSegmentationCoreCxxTests" "vtkSegmentationTest2")
set_tests_properties([=[vtkSegmentationTest2]=] PROPERTIES  LABELS "vtkSegmentationCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;16;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;0;")
add_test([=[vtkSegmentationHistoryTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSegmentationCoreCxxTests" "vtkSegmentationHistoryTest1")
set_tests_properties([=[vtkSegmentationHistoryTest1]=] PROPERTIES  LABELS "vtkSegmentationCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;17;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;0;")
add_test([=[vtkSegmentationConverterTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSegmentationCoreCxxTests" "vtkSegmentationConverterTest1")
set_tests_properties([=[vtkSegmentationConverterTest1]=] PROPERTIES  LABELS "vtkSegmentationCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;18;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;0;")
add_test([=[vtkClosedSurfaceToFractionalLabelMapConversionTest1]=] "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/MINS" "--launch" "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/Slicer-build/bin/vtkSegmentationCoreCxxTests" "vtkClosedSurfaceToFractionalLabelMapConversionTest1")
set_tests_properties([=[vtkClosedSurfaceToFractionalLabelMapConversionTest1]=] PROPERTIES  LABELS "vtkSegmentationCore" _BACKTRACE_TRIPLES "/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/ExternalData.cmake;325;add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/CMake/SlicerMacroSimpleTest.cmake;63;ExternalData_add_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;19;simple_test;/home/blvksh33p/Documents/Slicer-SuperBuild-Debug/slicersources-src/Libs/vtkSegmentationCore/Testing/CMakeLists.txt;0;")
